### ISSUE TITLE
Files in tree unmarked (new/changed) after switcher to other window

### ISSUE THREAD

**Issue by silentsokolov** [atom/atom#10757]
Also:

1) Change & save file:

![c0c2c2476b](https://cloud.githubusercontent.com/assets/398939/12951199/36697138-d022-11e5-9171-3927c6126c72.jpg)

2) Switch to other windows `cmd + Tab` (finder/chrome/other)

![f153884301](https://cloud.githubusercontent.com/assets/398939/12951210/3fe09304-d022-11e5-859e-38e7d6fc8f78.jpg)

3) Save again `cmd + S`

![c0c2c2476b](https://cloud.githubusercontent.com/assets/398939/12951199/36697138-d022-11e5-9171-3927c6126c72.jpg)

Mac OS X
Atom 1.5.0
Packages:
atom-beautify@0.28.22
autocomplete-python@1.6.1
file-icons@1.6.14
git-plus@5.13.0
language-gettext@0.6.1
linter@1.11.3
linter-flake8@1.10.1
merge-conflicts@1.3.7
project-manager@2.7.6
toggle-quotes@1.0.0

**Comment by hultberg** [comment]
This has been reported #10755 and atom/tree-view#725

**Comment by tclemos** [comment]
I'm facing a similar problem, but in an inverse situation, a lot of unchanged files was been shown as CHANGED, but when I click over them forcing them to open, the status is refreshed to UNCHANGED, after an interaction with a folder(e.g  folding) cause the refreshed file with no changes to become CHANGED again.

I've downloaded the Atom 1.4.3 and in the exact same situation this problem doesn't happen, this was probably broken between 1.4.3 and 1.5.0.

This feature is one of the bests and this problem is so annoying.

I've tried disable all packages, even the Core packages letting only the settings-view, but it doesn't fixed the problem, only the downgraded fixed.

I will keep using Atom 1.4.3 until it get fixed.

**Comment by hultberg** [comment]
As of 1.5.1 and 1.6.0-beta1 I'm not having this problem, solved for me. :+1:

**Comment by silentsokolov** [comment]
The problem occurs, when opening multiple folders

It's OK:
 
![1](https://cloud.githubusercontent.com/assets/398939/12973316/85f9080e-d0bc-11e5-9dd1-eaf19362f4e9.jpg)

It's failed:

![2](https://cloud.githubusercontent.com/assets/398939/12973321/935947fc-d0bc-11e5-8499-2957a77839a5.jpg)

1.5.1 and 1.6.0-beta1

**Comment by joshaber** [comment]
We just released 1.5.3 which fixes this. Thanks for the reports and patience!

![](http://www.reactiongifs.com/wp-content/uploads/2013/04/clumsy.gif)

**Comment by tclemos** [comment]
@joshaber hahaha, nice gif!
Thanks for the fix! :)
In my case, the version 1.5.1 already has the fix!

**Comment by arcticicestudio** [comment]
* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?

### Description
The issue is still left in another form.
When you're using the "Search in Directory" function to multi-edit/find-and-replace files the status of the edited files won't change, but only if you open a edited file.
All changed files are only marked as changed if you reload the whole window/view.

### Steps to Reproduce

1. Create a local test repository, you can use this script:
```shell
mkdir test-project && cd test-project
for ((i=0;i<=15;++i)); do touch test-file-$i; echo v1.2.3 > test-file$i; done
git init
git add .
git commit -m "Initial commit"
```
2. Add the project folder to the atom tree-view
3. Use the "Search in Directory" function, search for `v1.2.3` and replace all with `v1.2.4`
4. Confirm the multiple file edit dialog
5. The changed files in the tree-view are still uncolored, but if you open a edited file it will be marked as changed in the tree-view.
6. Reload the window/view (command palette: "Window: Reload")
7. Only now all edited files will be marked as changed
8. You can also reproduce
[Uploading github-atom-issue-10757-reopen.webm…]()
 the same issue in reversed form if you re-edit the files by replace all `v.1.2.4` with `v1.2.3` again and the files will still be marked as changed.

Screencast (Sorry for slow speed, but GitHub doesn't support `.webm` format upload)
![github-atom-issue-10757-reopen](https://cloud.githubusercontent.com/assets/7836623/13378618/21cc6b3e-de0c-11e5-924b-3d2826c12234.gif)

**Expected behavior:**
All edited files should be marked as changed immediately.

**Actual behavior:**
The edited files will be marked as changed only if you open each of them or reload the whole window/view.

### Versions
I noticed this issue first in version `1.4.1`.
I've tested in version `1.5.3` and the issue still remains.
