### ISSUE TITLE
-W is an invalid option for pwd

### ISSUE THREAD

**Issue by singingwolfboy** [atom/atom#11756]
I'm running Atom 1.8.0 beta 3 on Windows 7. It works, but when I try to launch it using the `atom` shell command, I get this failure:

```
{ ~ }  » atom                                                                                   ~
/cygdrive/c/Users/Linda/AppData/Local/atom/bin/../app-1.8.0-beta3/resources/cli/atom.sh: line 3: pwd: -W: invalid option
pwd: usage: pwd [-LP]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
```

I'm using [babun](http://babun.github.io/) as my shell, which may be part of the problem. I believe the failing line of code is [resources/win/atom.sh on line 3](https://github.com/atom/atom/blob/master/resources/win/atom.sh#L3). It doesn't look like `-W` is a standard flag for the `pwd` command.

Can anyone else reproduce this issue?

**Comment by damieng** [comment]
I think the reality is we can only support so many windows Bash shells. We've done a ton of work to get things working with MSYS, MSYS2, Cygwin and MinGW.  Have to draw the line somewhere.

**Comment by singingwolfboy** [comment]
@damieng: [babun](http://babun.github.io/) is built on Cygwin, so if Atom is supposed to work on Cygwin, I would expect it to work with babun as well. Can you verify that Atom is still working properly with Cygwin?

**Comment by damieng** [comment]
Confirmed also broken on Cygwin now.  Given the lack of uniformity between these bash-like environments and the constant attention they need I'm not sure we should actively support any.

**Comment by singingwolfboy** [comment]
@damieng: Is Atom a project that GitHub officially supports, or is it a community-supported open source project? If it's an official GitHub project, then I wonder if we could find a project manager to prioritize Windows support. If it's a community-supported project, then I'm not sure exactly what "actively supported" means one way or another. If people are willing to contribute fixes to the project, shouldn't they be accepted?

**Comment by damieng** [comment]
I can't speak for GitHub - you'd have to ask them but I do always take a look at the Windows PRs - there is only one right now which is pending some other important Windows related work (getting specs running)

Sorry for sounding frustrated - getting bash working working with the `--wait` on Windows has been painful. Atom has a built-in feature that basically causes it to quit if another copy of atom is running - after telling the other one to open the file. To work around this --wait on Linux uses signals - we have no such facility on Windows and have had to use PowerShell but getting the PowerShell script to be reliably called from various versions and distributions of Bash on Windows has been cat and mouse.

It looks like we *should* be able to detect Cygwin in the script and then do `cygpath . -a -w` to achieve the same result as `pwd -W`

**Comment by damieng** [comment]
@singingwolfboy Can you type the following two commands in to your bash and paste the results here? Ditto anyone else who has a variant not already in the list that follows;

```bash
uname -a
pwd -W
cygpath . -a -w
```

For reference, the other platforms I have access to right now are:

### Latest Cygwin download
```
CYGWIN_NT-10.0-WOW dpg-desk 2.5.1(0.297/5/3) 2016-04-21 22:12 i686 Cygwin
-bash: pwd: -W: invalid option
c:\cygwin\home\damie
```

### MSYS install/GitHub Desktop Shell in Bash mode
```
MSYS_NT-10.0 dpg-desk 2.5.0(0.294/5/3) 2016-03-01 13:48 x86_64 Msys
C:/msys64/home/damie
C:\msys64\home\damie\
```

### MinGW install
```
MINGW32_NT-10.0 dpg-desk 2.5.0(0.294/5/3) 2016-03-01 13:48 x86_64 Msys
C:/msys64/home/damie
C:\msys64\home\damie\
```

### Git 2.8.2.windows.1 Bash
```
MINGW64_NT-10.0 dpg-desk 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
C:/Users/damie
C:\Users\damie\
```

**Comment by singingwolfboy** [comment]
Just upgraded my test machine from Windows 7 to Windows 10 before I saw your comment. Here's what I get from running those commands via [babun](http://babun.github.io/):

```
{ ~ }  » uname -a
CYGWIN_NT-10.0-WOW Linda-PC 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
{ ~ }  » pwd -W
zsh: bad option: -W
{ ~ }  » cygpath . -a -w
C:\Users\Linda\.babun\cygwin\home\Linda
```

**Comment by damieng** [comment]
### MSYS1 install
```
MINGW32_NT-6.2 DESKTOP-KRL6KF7 1.0.11(0.46/3/2) 2009-07-11 17:46 i686 Msys
C:/msys/1.0/home/damie
sh: cygpath: command not found
```

**Comment by damieng** [comment]
@singingwolfboy Can you try replacing your atom.sh in %localappdata%\atom\atom-1.whatever\resources\cli with the contents from  https://github.com/atom/atom/commit/0e5a4ffb6e34687eb8bd208e170564f5ffa4419c and let me know if that works for you?

**Comment by singingwolfboy** [comment]
@damieng: It doesn't work for me. I put the error message in the pull request you made. (I have no idea why that's a syntax error, or what the problem is!)

Unfortunately, I don't think I'll be able to do further testing on this, at least not right now. I'm visiting my parents, and testing this setup on their Windows computer, but I'm leaving today. I think/hope/assume that if you fix this problem for Cygwin, it will work for babun as well, but I totally understand that the Atom team has to limit the number of different configurations it can support. Thanks for your help on this!

**Comment by damieng** [comment]
Hi, that error is actually caused by Cygwin being given a script with Windows-style CRLF's instead of LF's. I've merged the PR and included a line to tell git to leave the .sh line endings as LF. This should now work and be in the next full release.

**Comment by youurayy** [comment]
Also broke in 1.7.3 on Windows + Cygwin. Thanks for fixing this.

**Comment by damieng** [comment]
If you want the fix sooner you can over write your resources\cli\atom.sh
with the one from master :)

**Comment by youurayy** [comment]
command still not working in 1.8.0, possibly a different isssue:
![image](https://cloud.githubusercontent.com/assets/588573/16170259/9b92f3b6-3555-11e6-85b8-593e2f7a5bd5.png)

**Comment by damieng** [comment]
It didn't ship in 1.8. you can however overwrite your copy of atom.sh with
the one in resources/windows from master and see if that works.
