### ISSUE TITLE
Why is atom.exe trying to run at windows startup without launching?

### ISSUE THREAD

**Issue by srikar-s** [atom/atom#12360]
Hello,

I find that Atom installation has automatically added itself to the startup programs in Windows. I can see it is checked when I look under msconfig --> Startup.

When I reboot my windows machine, I get a security warning asking if I want to allow atom.exe to run. If I click on RUN, nothing happens, the editor does not launch. 

So my question is twofold:
1. What is atom.exe trying to do at startup?
2. Is it safe/OK to uncheck atom.exe in msconfig?

Thanks,
Srikar

**Comment by 50Wliu** [comment]
1. As far as I'm aware, nothing.  It shouldn't have added itself to the startup list - how did you install Atom?
2. Yes, it should be.

@damieng

**Comment by damieng** [comment]
Are you sure it's atom.exe and not atomsetup.exe?

We have a machine-wide AtomSetup.MSI file which will install atomsetup.exe and ensure that it runs automatically for all users to aid in deployment.

If this is what is running and you didn't mean to install it you can uninstall "Atom Machine-Wide Installer" (or something similar) from Add/Remove Programs in Control Panel.  This will leave normal Atom installed for the current user but stop the start-up check that ensures Atom is installed.

**Comment by srikar-s** [comment]
@damieng 

Yes.
To install atom, what I get on downloading it is "atomsetup.exe". I run it, and it doesn't ask me where I want to install it or anything. After a few minutes it's all configured.

I see that it gets installed here: C:\Users\<username>\AppData\Local\atom

The pop-up message at windows start-up though, points to a different location which is: 
C:\ProgramData\SquirrelMachineInstalls\atom.exe

Why does the installer place an exe in the ProgramData folder?

I did not encounter any MSI installers during the setup and neither do I see "Atom Machine-Wide Installer" in Control Panel.

**Comment by damieng** [comment]
Which version of Atom are you installing?  

There is a `--machine` flag you can pass to AtomSetup.exe that performs the behavior you mention so that all users who log into the machine get a copy (hence putting it in auto run) but you should have to manually specify that flag to get the behavior.

**Comment by srikar-s** [comment]
Atom version: 1.9.6
I did run the setup.exe as an administrator. But throughout the installation, there was no user prompt or anything I had to input.

**Comment by damieng** [comment]
Hmm, running as Administrator might be a thing.  

There is intentionally no user prompt in the installer, can you uninstall what you have and try running atomsetup.exe as a normal user to see if it behaves correctly?

**Comment by Ben3eeE** [comment]
I tested running AtomSetup.exe as administrator and it does indeed add atom.exe to the SquirrelMachineInstalls folder and to msconfig startup.

1.9.7 installer on Windows 7.

**Comment by srikar-s** [comment]
Yes. When I reinstalled without using "Run as Administrator", I found that the atom.exe was not added to SquirrelMachineInstalls and msconfig.

I am totally cool with atom.exe being provided in ProgramData for multi-user access - but msconfig should not be necessary, right?

Also, just as a matter of windows convention, would it not be better to provide the multi-login access under Program Files / Program Files (x86) instead of Program Data?

**Comment by damieng** [comment]
Limited users and non-administrators don't have write access to Program Files and even those that do get a UAC prompt which is why we install into appdata\local\atom.

There are a few reasons we can't share a copy of atom - one is somewhere shared without the permission issues especially when you consider we'd need write support to be able to update. Also some packages don't work with newer versions of atom so we ensure each user has their own copy of Atom.

Which leaves the question of how to install Atom for everybody on a machine.  

If you run the atomsetup.msi or use --machine or run atomsetup.exe as administrator we determine you wanted it for all users. Given we can't share a copy we instead put the installer into c:\programdata and then setup an auto-run so that every user logging in gets their own copy on this machine.

**Comment by oltmannsdaniel** [comment]
@damieng I tried it to run it everytime as administrator . But everytime the same result. The auto-update stuff kills the Application.

Maybe someone should remove the auto-update stuff.

**Comment by paulcbetts** [comment]
This is fixed in the latest version of Squirrel.Windows, which Atom is updating to shortly

**Comment by srikar-s** [comment]
@damieng Got it!
Btw, in any case, it should never be added to msconfig startup programs right? Also, in the current behavior, when we get the pop-up at windows startup, and we select "Run" instead of "Cancel", atom still does not launch.

**Comment by damieng** [comment]
It *has* to add the setup to startup programs or it would never install for any other user.  It is the setup auto-running not actually atom.  Yes, it won't launch either way as it's installing (or not if already installed)
