### ISSUE TITLE
Atom Dark Layout Issue on MacOS Sierra GM

### ISSUE THREAD

**Issue by louisjannett** [atom/atom#12634]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The Atom Editor uses a darker grey background color in the edited area of the editor and in the untouched area a normal grey color. This issue occurs in  
- Atom Dark
- One Dark
- Solarized Dark

<img width="795" alt="bildschirmfoto 2016-09-08 um 16 53 23" src="https://cloud.githubusercontent.com/assets/19536861/18354431/d82cf1a2-75e5-11e6-93d2-c40f35c35161.png">
### Steps to Reproduce
1. Open Atom 1.10.2 on MacOS Sierra Golden Master Release
2. Use a dark layout

**Expected behavior:** single backgound color grey

**Actual behavior:** 2 different background colours in one editor (dark and light grey)
### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS: MacOS Sierra Golden Master 64bit

**Comment by Greenek** [comment]
The same problem with atom-material-ui. Glitches are pretty random and sometimes after window resize problem disappears for a while.

![zrzut ekranu 2016-09-14 o 14 46 52](https://cloud.githubusercontent.com/assets/160300/18512575/1495d822-7a8a-11e6-894c-58ff905553b8.png)

Atom: 1.11.0-beta5
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
OS: macOS Sierra GM

**Comment by simurai** [comment]
Just from a gut feeling, this looks like some GPU rendering issue. Like if the textures that get sent to the GPU are missing in some places. Also because the width seems to be `256px` and I think that's how large GPU tiles are? /cc @as-cii 

![screen shot 2016-09-16 at 9 08 33 am](https://cloud.githubusercontent.com/assets/378023/18571492/c4eba418-7bed-11e6-9bc8-a012556e688d.png)

Electron (+ Chromium) just got updated, so that might fix this issue in Atom `1.12`.

**Comment by Greenek** [comment]
I made a little investigation and I found that problem affects probably all electron applications with dark elements, but only at monitors with custom color profiles (for example with non-native gamma value). This issue didn't occur before, so I guess it can be related with [Wide Color support](https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html#//apple_ref/doc/uid/TP40017145-DontLinkElementID_69) introduced in Sierra.

**Comment by thomasjo** [comment]
This is indeed caused by https://bugs.chromium.org/p/chromium/issues/detail?id=633805. Good find @Greenek!

@atom/feedback I marked this as `electron`, but technically speaking this is caused by rendering bug in Chromium. Do we leave this open here until it gets resolved upstream and ultimately makes it way through to us?

**Comment by Greenek** [comment]
BTW bug looks to be fixed in Chromium 54.0.2840.27 (beta) and higher. For now, the only solution for affected users is changing monitor's color profile.

**Comment by iolsen** [comment]
> Do we leave this open here until it gets resolved upstream and ultimately makes it way through to us?

Yeah let's leave it open until we get the Chromium fix or find another workaround.

**Comment by Greenek** [comment]
I found the solution. Problem disappears when Chromium has GPU rasterization enabled, so running Atom (or any other Electron app) with `--force-gpu-rasterization` or `--enable-gpu-rasterization` does the trick.

**Comment by pedantic79** [comment]
Another solution is to run atom with `--disable-gpu`.

**Comment by thomasjo** [comment]
Just a quick update; the underlying problem in Chromium has been [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=633805#c36), and should be released with Chromium 54.

This means once Electron bumps to that release, we'll resolve this issue once we bump to the corresponding Electron release.

**Comment by schrej** [comment]
As it seems to take a long time until Electron adopts Chromium 54 because there are some difficulties (see electron/electron#7744 and [the project](https://github.com/electron/electron/projects/2)), would it be possible to automatically start atom without GPU rendering when the os is MacOS Sierra?

**Comment by lee-dohm** [comment]
@schrej That isn't something that we would add to Atom as a default, no, because not everyone on macOS Sierra experiences this problem.

**Comment by zachbpd** [comment]
@lee-dohm I don't think everyone on Sierra experiences this issue. I know a lot of people who don't.

**Comment by lee-dohm** [comment]
@zachbpd Yes, that's exactly my point.

**Comment by schrej** [comment]
@lee-dohm @zachbpd Ah all right, i wasn't aware of that. Maybe this is related to which graphics are built into the macs (dedicated GTX 750M for me)?
Maybe a config option to disable gpu rendering would be an idea then if thats possible and not too hard to do? Or are there any macOS tricks i'm not aware of?

If you don't care for such temporary issues i'm fine with that by the way, just looking for a good solution as it is really annoying to start with `--disable-gpu` all the time and electron with chrome 54 will need a few months i guess.

**Comment by Greenek** [comment]
@schrej: 

> I found that problem affects probably all electron applications with dark elements, but only at monitors with custom color profiles (for example with non-native gamma value).

**Comment by lee-dohm** [comment]
@schrej Yeah, adding an option just to take it out again in a couple of releases isn't something that we want to do. Additionally, we prefer if `--disable-gpu` remains as an advanced user option rather than something that anyone can accidentally click on and then the performance of Atom is significantly impacted ☹️

**Comment by erwstout** [comment]
> I don't think everyone on Sierra experiences this issue. I know a lot of people who don't.

I'm also experiencing this issue, for what its worth. 

<img width="876" alt="screen shot 2016-12-22 at 10 50 50 am" src="https://cloud.githubusercontent.com/assets/9441913/21435030/9e11c7a8-c834-11e6-9106-b04ebee6e424.png">

**Comment by diedummydie** [comment]
As per @Greenek's advice, a temporary workaround if you launch Atom from the Terminal is to create an alias that always sets the enable-gpu-rasterization flag:
```sh
vim ~/.bash_profile
```
(or `nano ~/.bash_profile` if you're not a fan of vim)

Append the alias:
```sh
# added to fix Electron gpu tiles with macOS 10.12
alias atom="atom --enable-gpu-rasterization"
```

Save and close the file, then reload your profile:
```sh
source ~/.bash_profile
```

**Comment by xenio** [comment]
@diedummydie Is there a way to have the alias with --enable-gpu-rasterization and also have parameter passed to Atom?
I like to open file from terminal but also have --enable-gpu-rasterization
ie:
atom ~/.bash_profile
this isn't working if I have the alias with gpu enabled :(

**Comment by MikeBarnhardt** [comment]
I was able to fix this issue on a 2011 iMac 27" by going to `Apple` > `System Preferences...` > `Displays` > `Color` tab and selecting `iMac` as my color profile (from `Adobe RGB (1998)`).

You may need to select `Show profiles for this display only` to see it.

**Comment by razchiriac** [comment]
I was having this issue too on my MBP Retina. Fixed it by changing my display color settings to the default Color LCD.

**Comment by Codelica** [comment]
FWIW the Electron v1.5 beta that was first cut Jan 24th includes the move to Chrome 54.0.2840.101 which should have the fix.   A v1.5.1 beta was cut on Feb 6th and is the latest release for 1.5.x, so hopefully out of beta soon.   They seem to also have a v1.6.x beta going that's using Chrome 56.0.2924.87 and is at v1.6.3 beta as of yesterday.

**Comment by danielbayley** [comment]
Also affects [_predawn-syntax_](https://atom.io/themes/predawn-syntax) FWIW…

MacBook Pro Retina
macOS 10.12.3
Atom 1.16.0-beta0

**Comment by rlex** [comment]
@xenio probably late reply, but still
Alias doesn't take arguments, but you can write function
This will take one argument only
```
atom() {
    atom --enable-gpu-rasterization $1
}
```

And this will take all arguments
```
atom() {
    atom --enable-gpu-rasterization $@
}
```

**Comment by danielbayley** [comment]
> Alias doesn't take arguments

@rlex It doesn't need to if it's simply prepending the rest of the command…

`alias atom='atom --enable-gpu-rasterization'` would work just fine. Put it in a function if you need to rearrange or do something with the args…

**Comment by bdielman** [comment]
Seeing this issue for an external display running 1.17.0. Just updated and the problem was introduced.

**Comment by Codelica** [comment]
I does appear this was fixed in Electron, at least the new version that is used in VS Code (Insiders version) no longer has the issue.  https://github.com/Microsoft/vscode/issues/12473  So it should make its way into Atom eventually also.

**Comment by reaver585** [comment]
Same here. Changing display profile didn't help. Running Atom from command line helps - I hope next version will eliminate need to do this.

**Comment by aomega08** [comment]
Hi, running on 1.17.0. The problem appears only on external displays. If I move the window to the main Macbook display, it's ok. If I move it to the other screen, appears again.

`atom --enable-gpu-rasterization` did not solve for me. My Mac has "Radeon Pro 450 2048 MB
Intel HD Graphics 530 1536 MB"

**Comment by schrej** [comment]
@aomega08 As mentioned here a few times already, the issue appears on Screens with custom color profiles. You could just disable the custom profile on your external monitor. Also try `--disable-gpu` (also mentioned a few times already).

**Comment by montanaflynn** [comment]
It happened on my external asus display, I switched the custom profile to `sRGB IEC61966-2.1` and the problem went away or at least ins't noticable. None of the other color profiles worked though.

**Comment by reaver585** [comment]
Correction to my above post:

In fact `atom --enable-gpu-rasterization` does not solve the problem, `atom --disable-gpu` does.
I am also using external display.

**Comment by xenio** [comment]
I can't change the monitor profile, I have a calibrated monitor, and both --enable-gpu-rasterization and --disable-gpu doesn't work, my atom window is full of blocks :(

**Comment by epogue** [comment]
The latest Chromium/Electron changes seem to have fixed the issue in VSCode. Here's hoping those same changes make it into Atom soon! :smile:

For what it's worth, `--enable-gpu-rasterization` half-fixes the problem for me, but I still see some discoloration in inactive areas and during rendering. `--disable-gpu` seems to work, but I'm concerned that would cause a performance hit.

**Comment by tlmurphy** [comment]
I'm using two ASUS VH242H external monitors and changing the display profile worked for me.

**Comment by 50Wliu** [comment]
We are working to upgrade to an Electron version that fixes this issue - see #12696.  It's taking a long time because we want to leverage new features that will improve overall editor performance as well as fix as many regressions as we can find before finishing the upgrade.

**Comment by 50Wliu** [comment]
#12696 has been merged; master is now on Electron 1.6.9/Chrome 56 which fixes this issue.  Atom 1.19.0 _should_ contain the updated Electron version when it is released.

**Comment by MikeShi42** [comment]
fwiw I've been able to work around this by using `rgba` with a non-one alpha value to get around the tiling issue. Not sure why it works.

ex. 
```
atom-text-editor {
  background-color: rgba(36, 39, 46, 0.99);
}
```

**Comment by jonathonw** [comment]
I don't understand why, but I appear to also be able to work around this by forcing tab bar close icons to always be visible:

    li.tab div.close-icon {
        transform: scale(1.0) !important;
    }

Unlike the above, this doesn't leave artifacts in the text view gutter or in the tree view, and respects the editor background color set by the theme.

**Comment by olehermanse** [comment]
@xenio : 
> @diedummydie Is there a way to have the alias with --enable-gpu-rasterization and also have parameter passed to Atom via command line?
I like to open file from terminal but also have --enable-gpu-rasterization
ie:
atom ~/.bash_profile
this isn't working if I have the alias with gpu enabled :(

I found out that for some reason the advanced options like `--enable-gpu-rasterization` have to come after the file path.

**This doesn't work:**
```
atom --enable-gpu-rasterization ~/some_project 
``` 

**This works:**
```
atom ~/some_project --enable-gpu-rasterization
```

So a bash function that works for one argument is:
```
function atom-gpu {
    atom $1 --enable-gpu-rasterization ;
}
```

This might be a bug (?) as `atom --help` clearly states:
```
Usage: atom [options] [path ...]
```

( Of course you could also use the color profile fix that is mentioned above).

**Comment by frankny** [comment]
As reco'd by previous posters,

 I test out all three of these: 

 atom --enable-gpu-rasterization 
atom --force-gpu-rasterization
atom --disable-gpu

The only one that seems to have completely cleared the problem is disable-gpu. The other two dont get rid of the shading below the text. Image attached for reference. 

![screen shot 2017-06-05 at 9 34 02 pm](https://cloud.githubusercontent.com/assets/27034893/26810047/21ae0fa2-4a37-11e7-8d45-e0b6e40b771e.png)

**Comment by psabeckis** [comment]
Hello,

Until Atom hits 1.19 I solved this issue by applying opacity on the body tag in the styles.less. Didn't notice any incompatibilities and works great.

Code:
`body { opacity: 0.99 }`

**Comment by carlca** [comment]
Thank you @psabeckis. Your solution works a treat! It wasn't a serious problem because Atom still worked ok, but it annoyed me nonetheless. I'm happy now!

**Comment by SmeXhy** [comment]
Hoping for a fix soon!

**Comment by schrej** [comment]
@SmeXhy closed issue == issue fixed already
It's just not released yet, you'll have to wait for Atom 1.19 as written above multiple times.

**Comment by SmeXhy** [comment]
@schrej oh, allright, sorry.
