### ISSUE TITLE
Opening/reloading Atom focuses Tree View

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#14176]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening or reloading Atom focuses the Tree View instead of whatever was focused last, eg the file you were working on.

### Steps to Reproduce

1. Have the Tree View and a file open
2. Focus the file
3. Reload Atom

OR

1. Open an existing project that has files open with Atom

**Expected behavior:** After the open/reload finishes, to be able to continue typing like nothing happened

**Actual behavior:** Tree View has focus, so typing will trigger Tree View shortcuts

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.18.0-dev-a13887d25
Electron: 1.6.5
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.12.0.windows.1
visual studio 2015
```

### Additional Information

Windows 10 x64.  Not sure if this is a core bug or related to Tree View, so filing it here first.

**Comment by 50Wliu** [comment]
From #14216, it appears that this is a regression in 1.17.

**Comment by ozo2003** [comment]
still the same issue in 1.17-beta3 even if beta3 changes say that this was fixed, tried update and reinstall

**Comment by 50Wliu** [comment]
The focus issue fixed in beta3 was not related to this focus issue.

**Comment by iolsen** [comment]
Are people seeing this on platforms other than Windows? I can't reproduce it now on Mac on the latest master or 1.17-beta4.

**Comment by MichaelQQ** [comment]
Hi, I have same issue on Mac on 1.17-beta5.

However, after I uncheck **Focus On Reveal** in tree view's setting page, it works fine now.

**Comment by ozo2003** [comment]
i'm on Linux and still have the same issue in all availabale 1.17 beta versions

**Comment by samuel-ye** [comment]
Same issue on Mac 1.17 release, must uncheck Focus On Reveal to work

**Comment by nmfzone** [comment]
+1 Same here. OSX El Capitan. Atom 1.17.0. Must uncheck `Focus On Reveal` (on `tree-view`settings`).

**Comment by 50Wliu** [comment]
Ah, looks like it might be tied to the Focus on Reveal setting then, because I also have that enabled.

**Comment by valours** [comment]
On mac, my editor focused on tree, and I haven't possibility to edit file. Argh

**Comment by ggramlich** [comment]
I just updated to 1.25.0 and it looks like I have this issue as well.

```
> atom -v
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

> apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.7.4
```

Is there any workaround?

**Comment by rsese** [comment]
I was unable to reproduce with 1.34.0-nightly3 on macOS 10.12.6 (made sure `Focus On Reveal` was enabled).  Can you still reproduce @50Wliu?

**Comment by 50Wliu** [comment]
No more repro.
