### ISSUE TITLE
1.19.0-beta2: Cursor stucks at the first letter when using macOS Chinese IME

### ISSUE THREAD

**Issue by weihanglo** [atom/atom#14911]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cursor stuck at the first letter when using macOS built-in Chinese pinyin IME. 

We expect to input some characters first, and choose a word in IME panel. But from 1.19.0 (maybe beta 1), the cursor always stucks at the first letter. Although I can still type Chinese correctly under the circumstances., it is more helpful to see what you are typing out.

### Steps to Reproduce

**Expected behavior:** 

In 1.18.0, it looks well.

![atom](https://user-images.githubusercontent.com/14314532/27643849-ccf636da-5c54-11e7-9111-e7b09469cf10.gif)

**Actual behavior:** 

However, the cursor moves no more in 1.19.0-beta2.

![atom-beta](https://user-images.githubusercontent.com/14314532/27643959-0f04396e-5c55-11e7-838c-ac15ef580fbe.gif)

**Reproduces how often:** every time

### Versions

OS: macOS Sierra 10.12.5
Atom    : 1.19.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

At first, I dived into source code to search for the problem. Soon, I overwhelmed with the large codebase of Atom. I cannot figure out which commit producing this bug. If anyone can point out which part may produce this problem, I can help to solve it. Thanks :)

**Comment by maxbrunsfeld** [comment]
I'm guessing this is also related to the TextEditorComponent rewrite.

/cc @as-cii @nathansobo

**Comment by ykpythemind** [comment]
Similar problem occurs when using Google IME (Japanese)

Cursor stuck at the first letter, and I can see one letter when I'm typing.

- Mac OS Sierra 10.12.5
- Atom 1.19.0-beta2
- Google 日本語入力 2.20.2700.1

**Comment by as-cii** [comment]
It looks like this is a bug in Electron 1.6, but it should be fixed in Electron 1.7 (which is still in beta, though). Backporting a fix to 1.6 seems to be non-trivial, so I am afraid we will have to wait till Electron 1.7 hits stable in order to use it in Atom.

Meanwhile Electron 1.7 is in beta, though, it might be nice to get the ball rolling on the upgrade. Simply bumping the Electron version makes Atom crash, so we'll need dedicate some time to understand how to upgrade. /cc: @iolsen for prioritization.

**Comment by ethancfchen** [comment]
I'm using Mac Zhuyin IME, it's the same problem:
![8 -09-2017 10-15-08](https://user-images.githubusercontent.com/5051791/29102437-aaae99fc-7ceb-11e7-8f3f-db93ca354914.gif)
(I typed: 5j/ [space] jp6gj [space] bj4 [enter])

**Comment by nathansobo** [comment]
Anyone impacted by this on 1.19 should downgrade to 1.18 and disable updates until Electron 1.7 gets out of beta and we can upgrade. My apologies.

**Comment by akabekobeko** [comment]
The problem also occurs in [stable v1.19.0](https://github.com/atom/atom/releases/tag/v1.19.0) which was released as a stable version.

My environment:

* Atom 1.19.0 x64
* macOS Sierra 10.12.6
* Google Japanese IME

It is regrettable that the problem reported in the beta version was not fixed and the stable version was released as it was.

It will be fixed by downgrading, but it will be difficult for general users who are not developers.

But, everyone has a mistake.

Based on this, if you are going to improve Atom, it would be nice to be able to easily downgrade.

**Comment by nathansobo** [comment]
> It is regrettable that the problem reported in the beta version was not fixed and the stable version was released as it was.

Yeah, unfortunately my understanding is that there was no way to really fix this without upgrading Electron, and the new version isn't ready. It should be pretty easy to downgrade to 1.18 by downloading it [from the releases page](https://github.com/atom/atom/releases/tag/v1.18.0). You can disable updates from the about dialog. I'm sorry to roll this to stable with this issue. Maybe we should have waited, but there were many improvements that we needed to get out there.

**Comment by akabekobeko** [comment]
It is possible to obtain an old version from the release page and downgrade it. But, what to choose from downloads is hard to understand.

I am a developer so I can understand what I need. However, many users obtained from https://atom.io/ will have difficulty selecting archives selecting to their environment.

Improvement plan:

1. Add rollup function to about dialog
2. Organize downloads on release page (in order of popular platform)
3. Publish old version to https://atom.io/ (Automatically check user environment like latest version)

However, returning to the old version is a risk. Normally it is preferable not to degrade the latest version.

`3` seems to be good in these plans. How about placing older version links after warning text explaining the risk?

**Comment by EMLVIRUS** [comment]
If I understand things correctly, this issue seems affecting all non-english IME.

**Comment by miaulightouch** [comment]
never thought this bug would impact my daily work.

**Comment by pollyduan** [comment]
i has downgraded to 1.12 directly

**Comment by DarkNami** [comment]
yes, this issue affecting Microsoft Windows IME (Chinese, Japanese), too.

**Comment by tos-kamiya** [comment]
This issue is also reproduced on Ubuntu Gnome with a Japanese IME (namely fcitx-mozc). I have downgraded to Atom 1.18.

**Comment by nathansobo** [comment]
This was a process failure on our part. I misunderstood the magnitude of the issue when I saw it and it got lost in the shuffle. We really value our CJK users and I apologize. We have a workaround for the Chromium bug in the works via #15265 that should go out as a hotfix early next week so everyone can update.

**Comment by buuug7** [comment]
in 1.19.0-beta2, this will be fixed?

**Comment by Ben3eeE** [comment]
@buuug7 It will be fixed in the next round of hotfix releases. Atom 1.19.1 and 1.20.0-beta2. They should both be released early next week,

**Comment by buuug7** [comment]
@Ben3eeE i can't wait (-_-

**Comment by akabekobeko** [comment]
I checked that the problem was fixed in Atom v1.19.1.
Thank you very much!!!

**Comment by ethancfchen** [comment]
Mac Zhuyin IME fixed on 1.19.1, great job, thanks!

![2017-08-15 09 58 03](https://user-images.githubusercontent.com/5051791/29299389-e1d220d4-81a0-11e7-968d-246f4c7f1e7c.gif)

**Comment by miaulightouch** [comment]
Thank god it works!

**Comment by weihanglo** [comment]
It works! Thanks a lot!

**Comment by buuug7** [comment]
Great job , i removed sublime text from my mac and embrace Atom.

**Comment by tos-kamiya** [comment]
Thanks! Atom 1.19.1 works fine with a Japanese IME (fcitx-mozc) as far as I've tried it on a clean installation of "ubuntu-ja-17.04-desktop-amd64" on VirtualBox.

**Comment by Ben3eeE** [comment]
Thanks to everyone for reporting back that it is working now :heart: and apologies for the issue :bowing_man:

**Comment by xionglun** [comment]
Atom 1.19 works fine, but after upgrade to 1.20.0, this problem occurs again.

I use **[squirrel](https://github.com/rime/squirrel)** and macOS 10.12.6 (Atom version, 1.20.0)

**Comment by Ben3eeE** [comment]
/cc: @ungb @rsese Can you check :point_up: with Atom 1.20?

**Comment by ungb** [comment]
I'm unable to see this issue in atom 1.20.0.  
on 1.20.0
![ime](https://user-images.githubusercontent.com/5624870/30604864-ef5eee4e-9d20-11e7-8ace-8d6ad21e8558.gif)

**Comment by ungb** [comment]
Using Squirrel that you linked to, I was unable to repro the issue in Atom 1.20.0.  Can you attach image or gif of what you're seeing?

![rine](https://user-images.githubusercontent.com/5624870/30605133-db0464fa-9d21-11e7-9610-29fe21923dd5.gif)

**Comment by xionglun** [comment]
@ungb It's obvious, the popup jump from top left corner to the bottom of line.
You can compare on different versions.

**Comment by ungb** [comment]
ahh I see.  Not a problem!  Can you create a new issue for it @xionglun?  you also should link to this one so  it will give context on the issue.

**Comment by xionglun** [comment]
@ungb OK, I have created a new [issue](https://github.com/atom/atom/issues/15696).
