### ISSUE TITLE
Atom Update Doesn't Remove Old Version

### ISSUE THREAD

**Issue by popey456963** [atom/atom#15320]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Atom folder within AppData contains multiple different versions of Atom.

### Steps to Reproduce

1. Install Windows version.
2. Wait for new update to be released, observe old version still exists

**Expected behavior:** Old version should be removeed

**Actual behavior:** Old version remains
**Reproduces how often:** As far as I can tell, I have all major & minor releases since I installed Atom, so 100%.
### Versions

- 1.18.0
- 1.19.0
- 1.19.1

### Additional Information

Windows 10, 64-bit, Professional.

![](https://puu.sh/xaO9j/547f85e8b8.png)

**Comment by rsese** [comment]
Hmmm, according to https://github.com/atom/atom/issues/4588, you should have at most 2 versions?  I just checked my computer and I also have 1.18.0, 1.19.0, and 1.19.1 but I definitely had Atom installed back to at least 1.16 (though I'm only 99% sure I hadn't deleted directories when doing some testing).  

That issue is pretty old though so I'm not sure if it's still accurate but that's what I see on my machine.   @Ben3eeE are things about the same on your Windows machines?

**Comment by popey456963** [comment]
@rsese My installation is only a couple of weeks old, it's more than possible that it's restricted to two (major)/three (all) versions.  Is there a reason for this?

**Comment by Ben3eeE** [comment]
@rsese I only have 1.19.0 and 1.19.1 on my machine right now. I've had more than in the past though, can not remember ever having more than 3. But I do a lot of uninstalling, installing and reinstalling so my machine would not be representative of an average user. I run the installer several times per day on an average day. Uninstalling is not that frequent.

@popey456963 

* When you start Atom are you always starting the latest version? You can check the version from the Help menu -> About Atom.
* Let us know if 1.18.0 is still there when you install 1.19.2 ⚡️

**Comment by popey456963** [comment]
@Ben3eeE Using 1.19.1, will keep you posted when 1.19.2 is released whether anything changes!

**Comment by KammererTob** [comment]
I am on version 1.19.2 and there still are four versions:
![image](https://user-images.githubusercontent.com/1510949/29486766-3fd8a0ea-84ee-11e7-8705-ee7788ecddfa.png)

**Comment by ashthespy** [comment]
I'm on `1.19.3` and now have 5 versions from `1.18.0` in `AppData\atom`
Furthermore, in `AppData\atom\packages` the found the `.nupkg` files as well
```
atom-1.19.0-delta.nupkg
atom-1.19.0-full.nupkg 
atom-1.19.1-delta.nupkg
atom-1.19.1-full.nupkg 
atom-1.19.2-delta.nupkg
atom-1.19.2-full.nupkg 
atom-1.19.3-delta.nupkg
atom-1.19.3-full.nupkg 
```

**Comment by 50Wliu** [comment]
Can anyone who's experiencing this please upload their `SquirrelSetup.log`?

**Comment by popey456963** [comment]
@50Wliu I reinstalled Atom a few weeks ago, so I'm not sure if this is helpful to you, but [this is my squirrel log](https://hastebin.com/sugopihani.pas)

**Comment by otherjoel** [comment]
I am on Windows 10 Pro (1703, 64bit) and experiencing this as well. My `SquirrelSetup.log` is about 12MB, you can download it at <https://transfer.sh/TtwGk/SquirrelSetup.log> (link good for 14 days).

Right now in `C:\Users\Joel\AppData\Local\atom` I see

* `app-1.17.2` (82MB)
* `app-1.18.0` (617MB)
* `app-1.19.1` (606MB)
* `app-1.19.3` (608MB)
* `app-1.19.4` (606MB)

**Comment by TangSteven** [comment]
Windows 10
Atom Beta 1.20.0-beta5
app-1.19.0-beta7
app-1.20.0-beta2
app-1.20.0-beta3

**Comment by 50Wliu** [comment]
@paulcbetts maybe you could shed some light here?  `cleanDeadVersions` is failing with `ApplyReleasesImpl: Coudln't run Squirrel hook, continuing: C:\Users\Joel\AppData\Local\atom\app-1.19.1\atom.exe: System.OperationCanceledException: The operation was canceled.` and `ApplyReleasesImpl: Failed to clean dead versions, continuing anyways: System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by giocard** [comment]
Hi, 
I am experiencing the same issue. I don't know if this is relevant, but if I try to delete manually an older version I get a warning message that the name of some files are too long for the recycle bin, and then it hangs up while trying to delete them. My current workaround is to delete each subdirectory individually.

**Comment by ashthespy** [comment]
@giocard Should be way easier from the command line ;-)
```
cd %LOCALAPPDATA%/atom
rmdir /s /q app.1.19.5
```

**Comment by the-j0k3r** [comment]
Ill add a me too to this conversation.

5 previous versions present not including 1.20.1 update that literally was downloading.

I deleted 1.6GB of what seems useless 0's and 1's And I was wondering where my disk space was going so fast.

**Comment by h0rn3z0r** [comment]
I guess this bug will kill my SSD soon, since we cannot change installation directory, this folders take much space and extremely reduce it's resource cause of big number of write/read operations (each folder contains ~40000 files).

**Comment by the-j0k3r** [comment]
@h0rn3z0r you logic escapes me, how would this bug which is not deleting any of the old dirs cause high read/write operations?

Isnt this bug actually preventing those operations in the first place?

**Comment by mattfelsen** [comment]
I'm on Win 7 Pro & have these versions, totaling 3.82GB of disk space for the entire `AppData/Local/atom` folder:
- app-1.19.3
- app-1.19.5
- app-1.19.7
- app-1.20.0
- app-1.20.1

Here's my `SquirrelSetup.log` log: [https://pastebin.com/kJ4RxqAZ](https://pastebin.com/kJ4RxqAZ)

**Comment by cengizhan** [comment]
atom, vs-code or other programs which includes tons of files which change with each update will reduce ssd life span. i use them as portable on a normal hdd. 

annoying "node_modules"

**Comment by h0rn3z0r** [comment]
@the-j0k3r Right, I meant that I need to periodically clean up these folders cause of space lack which leads to a lot of write operations. Whole Windows folder contains as much files as three atom releases. And if this bug is fixed, this problem will exist. But this relates to whole atom structure and how updates are delivered :(
Portable vesion is a good workaround.

**Comment by popey456963** [comment]
@h0rn3z0r If you're concerned with the size of `node_modules`, that's more of a node issue as opposed to anything else.  There's an issue tracking it over at nodejs/node#14872.  It's probably best to limit this discussion to atom update issues only. 🙂

**Comment by lmao-emerald** [comment]
Same here. Windows 10 64 Bits. 
![image](https://user-images.githubusercontent.com/18596778/30660766-432361c8-9e42-11e7-874f-dd396633d071.png)

**Comment by the-j0k3r** [comment]
Like @ashthespy https://github.com/atom/atom/issues/15320#issuecomment-324899459 I also found the ```.nupkg``` files for the releases as well

Here's a pretty picture :/

![nupkg](https://user-images.githubusercontent.com/31389848/30732697-a682711c-9f6b-11e7-9535-6c1b70516337.PNG)

Thats another 648MB ontop of the Gigabytes for the actual old installs.

**Comment by ashthespy** [comment]
Logs - the answer to all issues! 

<details>
<summary> SquirrelSetup.log snippet </summary>

```
2017-09-08 11:23:00> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:00> Program: Fetching update information, downloading from https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:00> CheckForUpdateImpl: Using existing staging user ID: 318c3588-d795-543b-af69-4245692dfa5f
2017-09-08 11:23:00> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:00> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.6&id=atom&localVersion=1.19.6&arch=amd64
2017-09-08 11:23:02> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-delta.nupkg
2017-09-08 11:23:25> UpdateInfo: Couldn't get release notes for:atom-1.19.7-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Ash\AppData\Local\atom\packages\atom-1.19.7-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-09-08 11:23:25> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:25> Program: Starting update, downloading from https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:25> Program: About to update to: C:\Users\Ash\AppData\Local\atom
2017-09-08 11:23:25> CheckForUpdateImpl: Using existing staging user ID: 318c3588-d795-543b-af69-4245692dfa5f
2017-09-08 11:23:25> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:25> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.6&id=atom&localVersion=1.19.6&arch=amd64
2017-09-08 11:23:26> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-delta.nupkg
2017-09-08 11:23:59> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-09-08 11:23:59> CheckForUpdateImpl: Using existing staging user ID: 318c3588-d795-543b-af69-4245692dfa5f
2017-09-08 11:23:59> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.6
2017-09-08 11:23:59> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.6&id=atom&localVersion=1.19.6&arch=amd64
2017-09-08 11:23:59> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-full.nupkg
2017-09-08 11:24:21> ApplyReleasesImpl: Writing files to app directory: C:\Users\Ash\AppData\Local\atom\app-1.19.7
2017-09-08 11:24:33> LogHost: Rigging execution stub for atom_ExecutionStub.exe to C:\Users\Ash\AppData\Local\atom\atom.exe
2017-09-08 11:34:03> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Ash\AppData\Local\atom\app-1.19.7\atom.exe]
2017-09-08 11:34:12> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: MATLAB R2016b.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Mozilla Thunderbird.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Spotify.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2017-09-08 11:34:12> ApplyReleasesImpl: Fixing up tray icons
2017-09-08 11:34:12> ApplyReleasesImpl: cleanDeadVersions: for version 1.19.7
2017-09-08 11:34:12> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.19.6
2017-09-08 11:34:12> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.19.7
2017-09-08 11:34:17> ApplyReleasesImpl: Failed to clean dead versions, continuing anyways: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_2.<cleanDeadVersions>b__8(Tuple`2 p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_0.<<cleanDeadVersions>b__7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<cleanDeadVersions>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
```
</details>
<br><br>



Found an [Squirrel issue](https://github.com/Squirrel/Squirrel.Windows/issues/1024) that also got the same issue, and it's been fixed in https://github.com/Squirrel/Squirrel.Windows/commit/db4676f4a7173e87609c5d76b1a97b084638f8a2 and should be pushed to [`v1.7.6`](https://github.com/Squirrel/Squirrel.Windows/compare/1.7.5...1.7.6)
And should be pushed to `electron-winstaller`  in [`v2.6.3`](https://github.com/electron/windows-installer/commit/8916b4d09170f27246035aed469500bfc849019b) which has now [been bumped up](https://github.com/atom/atom/commit/3aa27a6256ee71581f177336f40cf0df1c785314) 

Soo - this should be fixed in the next update! :-)

**Comment by the-j0k3r** [comment]
Dammed Squirrels and their nuts :), thx for update, though I admit I was starting to wonder. Will be looking forward for that

**Comment by ashthespy** [comment]
@the-j0k3r The dependency chain should be:
```
Atom
  └──  electron-winstaller
    └── Squirrel
```
So, while squirrel fixed the issue back in June with `v1.7.6` It got incorporated into `electron-wininstaller` only in `v2.6.3` which was only recently upgraded in Atom.

Makes sense? :-)

**Comment by the-j0k3r** [comment]
Not to me, because 2.6.3 https://github.com/electron/windows-installer/commits/master was added 20th of June, make sense to you why doesnt make sense to me?

**Comment by ashthespy** [comment]
But Atom started using `v2.6.3` only [7 days back](https://github.com/atom/atom/commit/3aa27a6256ee71581f177336f40cf0df1c785314)

**Comment by the-j0k3r** [comment]
Ah OK, Next Atom stable update will tell for sure, Im waiting sitting down :)

**Comment by iolsen** [comment]
This has shipped on beta, which will be stable soon.

**Comment by the-j0k3r** [comment]
@iolsen

I'm glad I was sitting down waiting for this beta to become stable when I received an update to Atom 1.21.0 this morning from 1.20.1 **in order to actually verify the assertions made that this was fixed in beta**.

**My Report after the update is**: This is still half broken as far as I can tell since **app-1.20.1** folder with **519 MB (544,339,555 bytes)** with 39,331 Files, 10,864 Folders is left behind.

![app](https://user-images.githubusercontent.com/31389848/31173896-4e099c6e-a901-11e7-987b-6721c7d14fd6.PNG)

The https://github.com/atom/atom/issues/15320#issuecomment-331367045 `.nupkg`  is cleared properly/

![nupkg](https://user-images.githubusercontent.com/31389848/31173902-54d88d02-a901-11e7-9495-d0afe2ce1ca7.PNG)

So 50/50 its still half broken.

Squirrel.log portion for update.
```
2017-10-04 12:06:45> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:45> Program: Fetching update information, downloading from https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:45> CheckForUpdateImpl: Using existing staging user ID: 9fe577bb-0c45-5c2c-b8a1-7afa676c6e49
2017-10-04 12:06:45> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:45> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.20.1&id=atom&localVersion=1.20.1&arch=amd64
2017-10-04 12:06:46> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.21.0-delta.nupkg
2017-10-04 12:06:53> UpdateInfo: Couldn't get release notes for:atom-1.21.0-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Joker\AppData\Local\atom\packages\atom-1.21.0-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-10-04 12:06:53> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:53> Program: Starting update, downloading from https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:53> Program: About to update to: C:\Users\Joker\AppData\Local\atom
2017-10-04 12:06:53> CheckForUpdateImpl: Using existing staging user ID: 9fe577bb-0c45-5c2c-b8a1-7afa676c6e49
2017-10-04 12:06:53> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:06:53> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.20.1&id=atom&localVersion=1.20.1&arch=amd64
2017-10-04 12:06:54> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.21.0-delta.nupkg
2017-10-04 12:07:24> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-10-04 12:07:24> CheckForUpdateImpl: Using existing staging user ID: 9fe577bb-0c45-5c2c-b8a1-7afa676c6e49
2017-10-04 12:07:24> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.20.1
2017-10-04 12:07:24> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.20.1&id=atom&localVersion=1.20.1&arch=amd64
2017-10-04 12:07:25> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.21.0-full.nupkg
2017-10-04 12:07:38> ApplyReleasesImpl: Writing files to app directory: C:\Users\Joker\AppData\Local\atom\app-1.21.0
2017-10-04 12:07:40> LogHost: Rigging execution stub for atom_ExecutionStub.exe to C:\Users\Joker\AppData\Local\atom\atom.exe
2017-10-04 12:09:27> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Joker\AppData\Local\atom\app-1.21.0\atom.exe]
2017-10-04 12:09:28> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-10-04 12:09:28> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-10-04 12:09:28> ApplyReleasesImpl: Examining Pin: Firefox Developer Edition.lnk
2017-10-04 12:09:28> ApplyReleasesImpl: Examining Pin: Snipping Tool.lnk
2017-10-04 12:09:28> ApplyReleasesImpl: File 'C:\Users\Joker\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
2017-10-04 12:09:28> ApplyReleasesImpl: Fixing up tray icons
2017-10-04 12:09:28> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-04 12:09:28> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-04 12:09:28> ApplyReleasesImpl: cleanDeadVersions: for version 1.21.0
2017-10-04 12:09:28> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.20.1
2017-10-04 12:09:28> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.21.0
2017-10-04 12:09:52> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.21.0
2017-10-04 12:09:52> Program: Fetching update information, downloading from https://atom.io/api/updates-x64?version=1.21.0
2017-10-04 12:09:52> CheckForUpdateImpl: Using existing staging user ID: 9fe577bb-0c45-5c2c-b8a1-7afa676c6e49
2017-10-04 12:09:52> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.21.0
2017-10-04 12:09:52> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.21.0&id=atom&localVersion=1.21.0&arch=amd64
2017-10-04 12:13:15> Program: Starting Squirrel Updater: 
2017-10-04 12:18:19> Program: Starting Squirrel Updater: 
```

```
$ atom --version  

Atom    : 1.21.0  
Electron: 1.6.9  
Chrome  : 56.0.2924.87  
Node    : 7.4.0

$ apm --version  

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 3.5.2
git 2.14.2.windows.1
visual studio
```

**Comment by otherjoel** [comment]
@the-j0k3r as discussed [above](#issuecomment-322844462), keeping two versions (current and one previous) is the designed behaviour, not a bug.

**Comment by the-j0k3r** [comment]
Thank you, missed that part, clearly ;) , I guess the acid test then is the next update; and I dont mean by that anything else, except I'm keeping an eye on it.

**Comment by david-in-perth** [comment]
Atom has now updated itself to 1.21.0 on my computer, and all of the old app-* directories are still there.
![screenshot of old app folders in Windows Explorer](https://user-images.githubusercontent.com/558809/31375814-5e896758-add5-11e7-9db2-05baeedbb712.png)

The old *.nupkg files are also still there.
![screenshot of nupkg files in Windows Explorer](https://user-images.githubusercontent.com/558809/31375982-e645ebbc-add5-11e7-9760-6630f8116a63.png)

So it looks like the problem isn't fixed.

**Comment by mattfelsen** [comment]
@david-in-perth silly question, but do those older folders actually contain files? At some point I did something (reinstalled?) which left a number of old folders, but they were mostly empty. There were a handful of files left that couldn't be deleted I suppose, but the folders were a few KB each, not ~500MB.

**Comment by the-j0k3r** [comment]
I would be interested in seeing @david-in-perth 's squirrel log also.

**Comment by schikore** [comment]
I've got 1.21.0, and I have 13 versions in total, apparently 11 of which refuse to be automatically deleted.  The relevant bits of my squirrel log:
```
2017-10-03 12:18:25> ApplyReleasesImpl: cleanDeadVersions: for version 1.21.0
2017-10-03 12:18:25> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.20.1
2017-10-03 12:18:25> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.21.0
2017-10-03 12:18:35> ApplyReleasesImpl: Failed to clean dead versions, continuing anyways: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_2.<cleanDeadVersions>b__8(Tuple`2 p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_0.<<cleanDeadVersions>b__7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<cleanDeadVersions>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
```

**Comment by rsese** [comment]
Thanks @schikore - can anyone else on this thread who had more than 2 old versions of Atom and who has updated to 1.21.0 or 1.21.1 confirm how things look now?   If you have more than 2 old versions, can you share your SquirrelSetup.log file?

**Comment by popey456963** [comment]
@rsese Can confirm, more than two versions on my system too.  https://hastebin.com/wipatiguxo.hs

I think this issue should be reopened.

**Comment by the-j0k3r** [comment]
> I think this issue should be reopened.

this issue is in wrong place, the people that need to fix it is https://github.com/Squirrel/Squirrel.Windows/issues/1024

It may as well be that its not supposed to remove all the previous versions automatically, who knows.I removed mine manually except the `.nupkg` bits and those were cleaned automatically.

If anything anyway its https://github.com/Squirrel/Squirrel.Windows/issues/1024 that needs reopening.

**Comment by the-j0k3r** [comment]
I can confirm that updating to 1.21.1 leaves the 1.20.0 directory, many errors on squirrel log.

Im now going to comment on https://github.com/Squirrel/Squirrel.Windows/issues/1024 and post all information there, maybe hey will reopen the issue  and with some luck some decent garbage collection will in-sue.

Anyone interested join me there, because this issue is filled in wrong place.

**Comment by ralsu091** [comment]
@the-j0k3r try Deleting the content of C:\Users\YOUR_USERNAME\AppData\Local\SquirrelTemp
On the next update of atom you will have two folders.

**Comment by the-j0k3r** [comment]
Ive done that already before 1.21.0 upgrade.

**Comment by tzarc** [comment]
I have 10 versions as of 1.21.1:

```
16/06/2017  08:21 AM    <DIR>          app-1.18.0
09/08/2017  06:30 AM    <DIR>          app-1.19.0
15/08/2017  12:34 PM    <DIR>          app-1.19.1
17/08/2017  01:08 PM    <DIR>          app-1.19.2
28/08/2017  10:54 PM    <DIR>          app-1.19.3
29/08/2017  06:54 AM    <DIR>          app-1.19.4
05/09/2017  12:04 PM    <DIR>          app-1.19.5
15/09/2017  12:20 PM    <DIR>          app-1.20.0
20/09/2017  09:13 AM    <DIR>          app-1.20.1
17/10/2017  08:49 AM    <DIR>          app-1.21.1
```

Last batch of entries in SquirrelSetup.log:
```
2017-10-17 08:48:10> Program: Starting Squirrel Updater: --download https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:10> Program: Fetching update information, downloading from https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:10> CheckForUpdateImpl: Using existing staging user ID: e727b08c-1867-5dd2-8302-682884660474
2017-10-17 08:48:10> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:10> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.20.1&id=atom&localVersion=1.20.1&arch=amd64
2017-10-17 08:48:11> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.21.0-delta.nupkg
2017-10-17 08:48:11> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.21.1-delta.nupkg
2017-10-17 08:48:24> UpdateInfo: Couldn't get release notes for:atom-1.21.0-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\nickb\AppData\Local\atom\packages\atom-1.21.0-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-10-17 08:48:25> UpdateInfo: Couldn't get release notes for:atom-1.21.1-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\nickb\AppData\Local\atom\packages\atom-1.21.1-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-10-17 08:48:25> Program: Starting Squirrel Updater: --update https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:25> Program: Starting update, downloading from https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:25> Program: About to update to: C:\Users\nickb\AppData\Local\atom
2017-10-17 08:48:25> CheckForUpdateImpl: Using existing staging user ID: e727b08c-1867-5dd2-8302-682884660474
2017-10-17 08:48:25> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.20.1
2017-10-17 08:48:25> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.20.1&id=atom&localVersion=1.20.1&arch=amd64
2017-10-17 08:48:26> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.21.1-delta.nupkg
2017-10-17 08:48:26> FileDownloader: Downloading file: https://atom.io/api/updates/atom-1.21.0-delta.nupkg
2017-10-17 08:48:54> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-10-17 08:2017-10-17 08:49:56> Program: Starting Squirrel Updater: --createShortcut atom.exe -l StartMenu
2017-10-17 08:49:56> ApplyReleasesImpl: About to create shortcuts for atom.exe, rootAppDir C:\Users\nickb\AppData\Local\atom
2017-10-17 08:49:56> ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\nickb\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk
2017-10-17 08:49:56> ApplyReleasesImpl: About to save shortcut: C:\Users\nickb\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk (target C:\Users\nickb\AppData\Local\atom\atom.exe, workingDir C:\Users\nickb\AppData\Local\atom\app-1.21.1, args , toastActivatorCSLID f859ea73-8d1d-59d0-89d7-06ee420a371f)
2017-10-18 15:24:52> Program: Starting Squirrel Updater: --download https://atom.io/api/updates?version=1.21.1
2017-10-18 15:24:52> Program: Fetching update information, downloading from https://atom.io/api/updates?version=1.21.1
2017-10-18 15:24:52> CheckForUpdateImpl: Using existing staging user ID: e727b08c-1867-5dd2-8302-682884660474
2017-10-18 15:24:52> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates?version=1.21.1
2017-10-18 15:24:52> FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES?version=1.21.1&id=atom&localVersion=1.21.1&arch=amd64
```

**Comment by the-j0k3r** [comment]
@tzarc post the issues about this bug at https://github.com/Squirrel/Squirrel.Windows/issues/1024, this is a Squirrel bug not Atoms.

**Comment by rsese** [comment]
I asked the team to take a look and like @the-j0k3r mentions, this is an issue in Squirrel and not something we can fix directly in Atom.  It does looks like for [some people](https://discuss.atom.io/t/increasing-size-of-users-local-atom-due-to-old-versions/47196/5) the old versions are cleaned up, but we can see that there are others where the cleanup isn't happening.  Though not ideal, in this case you can manually delete the old versions.

We may look out installer improvements in the future but there's no timeline for that.

**Comment by otherjoel** [comment]
I downloaded 1.21.1 today, and, for me at least, the auto-deletion of older versions seems to be working.

Prior to downloading this update, two weeks ago I had manually deleted all the old versions leaving only 1.21.0 and 1.20.1.

After downloading today's update, I have only 1.21.1 and 1.21.0—so, one current and one previous.

If people are hanging on to copies of versions _older than 1.21.0_ (when the purported upstream Squirrel fix was included in Atom) in hopes being able to watch them all get cleaned out automatically by "the fix", I would suggest deleting those manually as I did. I don't know how Squirrel does whatever it does, but I do see that each of these "old versions" folders contains its own copy of `squirrel.exe`, so perhaps those old copies still have the old bug and are never going to auto-delete.

**Comment by the-j0k3r** [comment]
> Prior to downloading this update, two weeks ago I had manually deleted all the old versions leaving only 1.21.0 and 1.20.1.

Yes that works, everything else, doesnt seem to... Again this is the wrong report, this is a squirrel bug.

@rsese please would you make one last post here pointing to https://github.com/Squirrel/Squirrel.Windows/issues/1024 and lock this? Its pointless trying to get the right attention when ppl dont go to the right topic.

**Comment by otherjoel** [comment]
> Again this is the wrong report, this is a squirrel bug

I definitely hear you beating that same “it’s a Squirrel bug” drum. But you don’t seem to be listening to what I’m saying.

Auto-delete **is now working**—but only for the old versions starting with 1.20.1. I just watched it work. Atom updated to 1.21.1 and it auto-deleted 1.20.1, keeping the current version and one previous (1.21.0).

**The Squirrel bug has actually been fixed**. But that fix doesn't propagate to the _old versions of Atom_ in your AppData folder (each of which has its own copy of squirrel). So everyone will have to manually delete those old versions this one time, then get on with their lives. There is no Squirrel fix that is going to magically clean those old folders, since—again—this is an Atom problem at this point, not a Squirrel problem.

**Comment by the-j0k3r** [comment]
> I definitely hear you beating that same “it’s a Squirrel bug” drum. But you don’t seem to be listening to what I’m saying.

I heard/read and understood and even gave you a reply.

**Comment by the-j0k3r** [comment]
Also for anyone interested the bug isnt fixed https://github.com/Squirrel/Squirrel.Windows/issues/1024#issuecomment-336494596

I have now 3  folders 2 old versions left behind + current.

**Comment by 50Wliu** [comment]
> But that fix doesn't propagate to the old versions of Atom in your AppData folder (each of which has its own copy of squirrel).

Unless I am misunderstanding the update code, only the version of Squirrel bundled with the Atom version you are updating from is used.  So it shouldn't matter how outdated the other Squirrel versions are.  As always, the SquirrelSetup log would be helpful in tracking down what's going wrong.

**Comment by the-j0k3r** [comment]
@50Wliu see https://github.com/atom/atom/issues/15664#issuecomment-338455782

Im linking this invalid bug report to issue #15664 because its been fixed in Squirrel upstream.

So please pass along to Atom team so they can update Squirrel framework to incude that fix and so the bug described here is properly dealt with.

**Comment by david-in-perth** [comment]
For the record, I can confirm that Atom is now automatically deleting everything but the two latest Atom versions on my machine.

I'm pretty sure that I never manually deleted any of the prior versions that were on my computer (because I wanted to be able to confirm that the fix worked), so I'm happy to regard this item as fixed now.

**Comment by cheTesta** [comment]
@david-in-perth actually...

![atom](https://user-images.githubusercontent.com/24191291/40124023-dd2dca74-5927-11e8-91cc-db5e14ee79c4.PNG)

**Comment by krcools** [comment]
I also still experience this issue:

![image](https://user-images.githubusercontent.com/10086147/44786395-44a56680-ab94-11e8-8ac8-ab4f0786786d.png)

**Comment by abelbraaksma** [comment]
@david-in-perth, I cannot see that. Definitely still happening on my machine, updated today. Here's what I have, including the 1.31.1 version. I was checking what was taking up so much space of my AppData and ~80% went to Atom...

![image](https://user-images.githubusercontent.com/16015770/46349310-f16e7a00-c651-11e8-8f71-f677549eccaf.png)

**Comment by montera** [comment]
Yes I have the same problem with atoms consuming a lot of disk space

**Comment by abelbraaksma** [comment]
@popey456963, can you reopen your issue? It seems to be inadvertently closed, the resolution didn't work (or didn't work well).

**Comment by rsnitsch** [comment]
Consuming 1,7 GB here with 3 distinct app-x.y.z folders in AppData\Local\atom.

**Comment by senpl** [comment]
It should be reopened. It is still issue in Windows 7.

**Comment by sww1235** [comment]
Noticing this issue as well on Windows 10. Have 1.39.1, 1.40.0 and 1.40.1 in %APPDATA%\Local\atom

**Comment by Hoppingmad9** [comment]
I currently have 1.29.0, 138.2, and 1.40.1
[SquirrelSetup.log](https://github.com/atom/atom/files/3689898/SquirrelSetup.log) was asked for before so here it is

**Comment by abelbraaksma** [comment]
@iolson, you closed this issue two years ago, but ever since there's been numerous reports that the fix didn't work. Can you reopen so that it can come into view again?
