### ISSUE TITLE
Clicking on either scrollbar moves the cursor in the editor

### ISSUE THREAD

**Issue by lydianchord** [atom/atom#15488]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Clicking on either scrollbar moves the cursor in the editor, which, as a side effect, deselects any text you've selected.

### Steps to Reproduce

1. Open any text file
2. Select some text
3. Click/drag on either scrollbar and note the position of the cursor

**Expected behavior:** Clicking on a scrollbar has no effect on the cursor's position

**Actual behavior:** Clicking on a scrollbar affects the cursor's position

**Reproduces how often:** 100% of the time

### Versions

```
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.5.2
git 2.12.2.windows.2
visual studio 2015
```

On Windows 10. This bug was also present in Atom 1.19.3

### Additional Information

It seems others started noticing this problem recently as well:
* https://discuss.atom.io/t/clicking-on-scrollbar-moves-cursor-in-the-editor-erratically/46732
* https://github.com/atom/atom/issues/3284#issuecomment-324958746

**Comment by Ben3eeE** [comment]
I can reproduce this in Atom 1.20.0-beta4 but not in Atom 1.18

**Comment by fasidOnGit** [comment]
@Ben3eeE  No, Now I have roll back to Atom 1.18 actually this error is from 1.19.3. Atom 1.18 works just fine.

**Comment by narcolepticinsomniac** [comment]
I reported this like a month ago [here](https://discuss.atom.io/t/scrolling-interval-irregularities/45822).

I am testing Atom for the first time, so I asked in the forum instead of posting an issue here. I assumed there's no way such an obvious bug would make it into stable, so this behavior must be some terrible "feature" I could turn off. 

How long has this bug been allowed to hang around, and how does it not drive you all crazy? I really want to give Atom a shot, but stable is too annoying to use currently. Tested 1.18 and scrolling is fine.

**Comment by as-cii** [comment]
@narcolepticinsomniac I apologize for this issue, I definitely agree this is a pretty bad experience. 

We have already merged the fix into master and will soon release a hotfix that addresses the problem.

**Comment by robertkern** [comment]
@as-cii I don't know if this has reappeared but in `1.23.0-beta.1` on macOS I experience the same problem - clicking on the scrollbar moves the cursor... took a while to figure out why I was losing so much from the copy/paste's I was doing.

**Comment by as-cii** [comment]
> I don't know if this has reappeared but in 1.23.0-beta.1 on macOS I experience the same problem - clicking on the scrollbar moves the cursor... took a while to figure out why I was losing so much from the copy/paste's I was doing.

Thanks for the report, @robertkern. I don't think we have touched that code path after the fix for this bug landed on master.

Can you reproduce this in safe mode? (e.g. `atom --safe`) Considering I am unable to reproduce this locally, I wonder if some package/theme is causing this issue. Thanks for your help! ⚡️

**Comment by robertkern** [comment]
Hi @as-cii thanks for taking a look. Tried in safe mode and i can still reproduce. To clarify, cursor only moves once when I first click on the scroll bar. If i try click on the scroll bar on the same line as the cursor, the cursor doesn't move. If i click on the scroll bar above or below the cursor, then the cursor will move to that line and stay there while i drag the scroll bar.

**Comment by as-cii** [comment]
Thanks for following up, @robertkern!

@ungb @rsese @Ben3eeE: can you help me reproduce the issue @robertkern is having? I still can't observe this locally, but if we could collect consistent repro steps we can prioritize working on a fix for this.

**Comment by rsese** [comment]
Just gave this a try on macOS 10.12.6 in safe mode with the same `1.23.0-beta1`based on this description:

> cursor only moves once when I first click on the scroll bar. If i try click on the scroll bar on the same line as the cursor, the cursor doesn't move. If i click on the scroll bar above or below the cursor, then the cursor will move to that line and stay there while i drag the scroll bar.

But wasn't able to reproduce.  @robertkern can you share a GIF or screencast that demonstrates this behavior in safe mode?  If the GIF or screencast shows mouse clicks (https://www.cockos.com/licecap/ does this), that would be ideal so we can see exactly how you're interacting with the scrollbar.

**Comment by ungb** [comment]
@as-cii I was able to repro this issue when set scroll to on `when scrolling` in `system settings` -> `general`.  I wasn't able to repro when scroll was set to always.  @robertkern  is this the same setting you have?

![image](https://user-images.githubusercontent.com/5624870/33568705-3a9c3cf8-d8dc-11e7-96af-eeced0d9bf5f.png)

**Comment by rsese** [comment]
Ohh nice @ungb - I have that setting as `Always` but when I switch to `When scrolling`, I see this behavior too.

**Comment by as-cii** [comment]
Nice work @ungb and @rsese! /cc @iolsen for reactive prioritization.

**Comment by robertkern** [comment]
Oh good find! Yes I have mine set to show `When scrolling` and if i set it to `Always` then I don't see this behaviour. Thanks!
