### ISSUE TITLE
Fixing scroll sensitivity on macOS trackpad

### ISSUE THREAD

**Issue by billyjanitsch** [atom/atom#16743]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Following up on #15567 and #16114 now that they've landed in a stable release.

The default scroll sensitivity on a macOS trackpad now now feels much closer to native scrolling! (yay) But I notice two issues:
1. Editor scrolling now feels _more_ sensitive than native scrolling, with the default sensitivity.
2. There's some visual jank while scrolling -- much more than in a browser.

I think (1) is partially caused by [this bit of code](https://github.com/atom/atom/blob/7e0635d2c0d4b50cb76e4eccd619ab1041e5c86d/src/text-editor-component.js#L1524), which resolves each scroll delta to a minimum of 1px. Trackpads fire scroll events very often, so unless you're scrolling very quickly, the deltas can easily be less than a pixel, especially after being multiplied by the sensitivity (default 0.4).

Scaling up these small deltas makes scrolling feel weird, because it prevents the trackpad from distinguishing between velocities greater than 0 but less than a certain value. What's the rationale for this scaling? I thought it might be to align everything to a pixel grid, but that doesn't seem for happen for anything larger than 1px.

Another factor in (1) is the use of `wheelDelta` over `delta`, introduced in #16114. It seems like on a macOS trackpad, the former is exactly 3x the latter, or 1.2x when multiplied by the default scroll sensitivity (0.4). This makes me think that `delta` is actually the correct value -- the default sensitivity is what's throwing things off. Sure enough, using `delta` with a sensitivity of 1 (or emulating this by setting the sensitivity to 0.33 with the current `wheelDelta` implementation) feels _much_ more natural.

I'm not sure how scrolling works for other platforms, but what's the meaning of the default value "40" in the first place? It seems like it should default to 100, and be adjustable by users as a percentage. That would let the scrolling code use `delta` to precisely replicate native scrolling. If that's too hard to change globally, we could at least make "40" equivalent to native for wheel scrolling by replacing `wheelDelta * scrollSensitivity` with `delta * (scrollSensitivity / 40) * 100`.

Happy to PR these changes if you agree with them.

I'm not sure what's causing (2) -- the Atom implementation of scrolling probably just isn't as fast as the native one.

cc @Ben3eeE @50Wliu @nathansobo

### Steps to Reproduce

Open an editor window and an Atom settings window in separate tabs, then switch between them while scrolling.

**Expected behavior:** identical to native scrolling

**Actual behavior:** too sensitive, & some jank

**Reproduces how often:** 100%

### Versions

Atom 1.24.0
apm 1.18.12
macOS 10.13.3

**Comment by Ben3eeE** [comment]
Thanks for opening this issue :bowing_man: 

We will definitely review a PR that makes these changes! `delta` is from my testing something we want to use or at least experiment with. `wheelDelta` was used before Atom 1.19 and when rewriting the editor rendering we changed to use `delta` by mistake. This caused a lot of issues with scrolling from users because it was not implemented correctly. We had the same implementation with a different property.

The reason we merged https://github.com/atom/atom/pull/16114 is because that is an implementation that has worked previously. To me this is something more of a quick fix to get more time to investigate `delta`-based  scrolling.

The biggest concern to making these changes is the big amount of possible configurations. I have only been able to test on Windows and Linux with a mouse. I don't have a mac or a laptop or any touchpad available to ensure that scrolling feels good across all platforms using both a mouse and a touchpad.

### Windows

When using a mouse and scrolling one notch of the wheel `wheelDelta` is 120.

For `delta` it depends on [`deltaMode`](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode).

* When `deltaMode` is `DOM_DELTA_PIXEL` and scrolling one notch `delta` is 100/3 * `linesToScroll`. So it's 100 with the default setting of 3 lines
* When `deltaMode` is `DOM_DELTA_PAGE` and scrolling one notch `delta` is 1
* `DOM_DELTA_LINE` is not used?

Configuring this is done in the Windows control panel mouse settings.

![image](https://user-images.githubusercontent.com/1058982/36246919-3279351e-1232-11e8-9df2-d854d6dc5b4f.png)

### Ubuntu 16.04

When using a mouse and scrolling one notch of the wheel `wheelDelta` is 120.

When using a mouse and scrolling one notch of the wheel `delta` is 53. I did not test much on Linux but this did not seem to be the same scrolling rate as native applications. I also couldn't find a way to configure this in the OS settings.

This small delta compared to the previous value of 120 caused a significant slowdown in scroll speed which raised many issues.

---

> what's the meaning of the default value "40" in the first place?

I'm not sure. You might be able to find some answers if you look in the git history.

> Trackpads fire scroll events very often, so unless you're scrolling very quickly, the deltas can easily be less than a pixel, especially after being multiplied by the sensitivity (default 0.4).

This was introduced in https://github.com/atom/atom/pull/15487. Maybe by mistake since we were still using an incorrect `delta`-based scrolling then? Would be interested to hear what you can find out!

**Comment by billyjanitsch** [comment]
@Ben3eeE thanks for the summary of the other platforms! Evidently I have a bit of digging to do. I'm traveling for a few weeks, but once I'm back to my home setup, I'll find a mouse and play around with Windows/Linux VMs.

I will go ahead and PR a reversion to #15487 for now, since it seems like that was only an issue because of the accidental switch from `wheelDelta` to `delta`, and only affects trackpads.

**Comment by nathansobo** [comment]
Did you have any luck tweaking the scroll sensitivity in the editor settings?

![screen shot 2018-05-02 at 1 28 10 pm](https://user-images.githubusercontent.com/1789/39544869-afac1ee6-4e0c-11e8-9645-c73ed772c6a3.png)

**Comment by edirpedro** [comment]
@nathansobo yes, i've tried the minimum value 10 and higher values, but it still happens a lot. It's not smooth as it is when using the trackpad.
