### ISSUE TITLE
MacOS Mojave: The text in the editor is dimmed / hard to read.

### ISSUE THREAD

**Issue by timothymarois** [atom/atom#17486]
I know this OS was just released as a developer beta. So that is why I am reporting this so it can be properly dealt with as most of us are developers. This is going to make a lot of developers uneasy about installing this OS unless this is fixed. 

### Description
The code within Atom using MacOS Mojave is very dim, stylesheet and syntax theme, UI theme do not effect the dim of the editor text. 

### Steps to Reproduce

1. Install Macos Mojave
2. Open Atom

**Expected behavior:** Readable text

**Actual behavior:** Code within Atom is very hard to read within the editor.

**Reproduces how often:** 100%

### Versions

1.27.2

Using the default "Light" theme

![screen shot 2018-06-07 at 11 39 09 pm](https://user-images.githubusercontent.com/2489333/41137922-029935a6-6aac-11e8-9cf8-48de676cee30.png)

Using Atom One Dark

![screen shot 2018-06-07 at 11 40 32 pm](https://user-images.githubusercontent.com/2489333/41137964-340cef9c-6aac-11e8-8819-696c5db0fb59.png)

*Note: The actual text appearing on screen is "dimmer" than what these snapshots look like*

**This does not look theme related** . Almost as if the text itself is just "dim" / "opacity"

**Comment by thomasjo** [comment]
Are you seeing similar rendering issues in Chrome on macOS Mojave on any specific websites?

**Comment by thomasjo** [comment]
@atom/maintainers My hunch is that this might have something to do with GPU rendering; there's been some fairly significant changes to Metal in macOS Mojave. I haven't had time to install the beta yet, but I'm guessing this will affect all Electron apps, potentially even Chrome/Chromium.

/cc @atom/electron-maintainers

**Comment by daviwil** [comment]
@timothymarois Could you try 1.28.0-beta3 also? There was a change to Chromium that affects UI colors, I'm curious to see if you get different results.

@thomasjo's idea sounds pretty likely to be true, I'll talk to the Electron folks and see if they're aware of it.

**Comment by timothymarois** [comment]
@thomasjo I haven't noticed any differences within Chrome itself, or specific websites. So far its only Atom which has the issue. I will check other Electron apps and see if the issue persist. 

@daviwil I have just tried the Atom Beta and the issue still there.

**Comment by timothymarois** [comment]
Yeah, so far it looks like its just Atom that is affected (from what I can see so far with Electron apps).

**Comment by simurai** [comment]
> @thomasjo My hunch is that this might have something to do with GPU rendering

Yeah, might be.

The text also looks really thin (for macOS) and based on the screenshot ☝️ above https://github.com/atom/atom/issues/17486#issue-330509576, there is no sub-pixel antialiasing:

No sub-pixel antialiasing | With sub-pixel antialiasing
--- | ---
![image](https://user-images.githubusercontent.com/378023/41208194-907e7082-6d5b-11e8-9566-94ca07d751cb.png) | ![image](https://user-images.githubusercontent.com/378023/41208243-308b3a88-6d5c-11e8-8ed0-4a2460f50e51.png)
Only grey scale | has red/orange and blue edges

**Comment by simurai** [comment]
Just saw VS Code's issue about Mojave's font rendering: https://github.com/Microsoft/vscode/issues/51132. The removal of sub-pixel antialiasing might be intentional, see this [tweet](https://twitter.com/siracusa/status/1004143205078597633).

My conclusion: Apple finally releasing a stand-alone monitor with retina screen. :stuck_out_tongue_winking_eye:

**Comment by mdeboer** [comment]
Have you tried adding this to Atom's stylesheet?

```less
atom-text-editor {
	-webkit-font-smoothing: subpixel-antialiased;
	// font-weight: 300; Optionally add this.
}
```

Should do the trick 👍

**Comment by vinkla** [comment]
This is also reported in Visual Studio Code: https://github.com/Microsoft/vscode/issues/51132 and could be related.

**Comment by swiknaba** [comment]
@mdeboer `-webkit-font-smoothing: subpixel-antialiased;` doesn't do the trick for me (Atom 1.28.0 x64)

**Comment by vinkla** [comment]
It seems Apple released [further updates to UI font smoothing](https://twitter.com/jnadeau/status/1018966229183184897) in Mojave Beta 4. The fonts now look bolder and are easier to read.

**Comment by lee-dohm** [comment]
Thanks for the update @vinkla 😀 

It sounds then like this has been fixed. Because of that, I'm going to close this issue. If anyone has any other concerns or questions. Please let us know and we can revisit :+1:

**Comment by vinkla** [comment]
It seems Apple have reverted their changes in beta 5 and the fonts now look thinner again.

https://github.com/Microsoft/vscode/issues/51132#issuecomment-408998612

**Comment by phyllisstein** [comment]
Seems like this might be worth reopening. As of the latest Mojave dev beta (11 I think?) this is what Atom looks like compared to Sublime:

<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/2207980/45725623-a486a000-bb89-11e8-9a5e-91c1f2cd467b.png">

The `defaults` command posted in the VSCode issue (`defaults -currentHost write -globalDomain AppleFontSmoothing -int 2`) doesn't do a whole lot of good either.

**Comment by joshtemple** [comment]
Agreed. Atom's editor with default settings looks pretty rough on non-Retina monitors after the Mojave update. I've tried increasing the `font-weight` property and setting `-webkit-font-smoothing: subpixel-antialiased`. These fixes help to some degree but don't restore the original clarity of the text, especially in panes or in the tree view.

**Comment by amercier** [comment]
The problem still appears on MacOS Mojave public release (9/24). Please reopen.

**Comment by daviwil** [comment]
Hey folks, could you try running this command and then restart Atom:

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

Hat tip to @alexanderyakusik in [this comment](https://github.com/Microsoft/vscode/issues/51132#issuecomment-424132330) for this possible fix!

**Comment by phyllisstein** [comment]
That seems to have done it! Thanks so much for forwarding the fix along!

##### Before
<img width="1372" alt="screenshot" src="https://user-images.githubusercontent.com/2207980/45982079-53612b00-c025-11e8-97e4-feef0f2c6464.png">

##### After
<img width="1372" alt="screenshot 1" src="https://user-images.githubusercontent.com/2207980/45982083-58be7580-c025-11e8-9efe-f5ec7bac3640.png">

**Comment by Red3nzo** [comment]
@daviwil Your command worked for me thank you! I couldn't stand the super thin text, not even my custom font packages where working, now they are.

**Comment by StuCowley** [comment]
@daviwil legend! That worked perfectly, I was beginning to start pulling my hair out over this and downgrade back to High Sierra

**Comment by shellbryson** [comment]
The "fix" above looks like a global config change, rather than a fix for Atom? It doesn't resolve anything given the potential impact on _other_ apps, surely?

**Comment by daviwil** [comment]
Yes, this is a global configuration change that effectively reverts a change that Apple made to font rendering which makes fonts look very thin on non-Retina displays.  This change has affected other Electron-based apps like VS Code, so until there's a general solution for all Electron apps, this workaround will have to suffice.

I'd love to know if anyone has noticed any negative effects to the fonts in native macOS applications after running this command and rebooting their machine!

**Comment by abdul-elah-js** [comment]
try increasing `font-weight` it worked for me .. just add 
```
atom-text-editor {
      font-weight: bold;
     // the rest of your styles
}
````
in your style sheet

**Comment by joshuahiggins** [comment]
For what it's worth, I'm finding this issue present on both retina and non-retina screens with Atom. I've tried a handful of other apps with the smoothing enabled and disabled and while I can see minor changes in some, Atom is _drastically_ different. 

![Imgur](https://i.imgur.com/OY669e4.png)

**Comment by samwalshnz** [comment]
Just going to leave this here: https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/

**Comment by agonzalezv** [comment]
If you don't want to mess with global config just install: 

https://github.com/braver/fonts

And change as per your liking. I'm currently using `office code pro light`.

**Comment by lee-dohm** [comment]
I've created [a FAQ](https://discuss.atom.io/t/macos-mojave-font-rendering-change/59058) for this on [Discuss, the official Atom message board,](https://discuss.atom.io)

**Comment by patoi** [comment]
Increasing font size could help.

**Comment by cebor** [comment]
There is an open PR at electron which eventually will fix this.

See: https://github.com/electron/electron/pull/15007

**Comment by timothymarois** [comment]
Does anyone know if this has been fixed? I restored back to MacOS High Sierra since I don't have time to deal with these changes. Apple has released the MacOs Mojave update. But I am very skeptical. Can anyone confirm its been resolved?

**Comment by mdeboer** [comment]
I never had any trouble to begin with on retina screens. You can simply adjust your stylesheet and set the font-weight to your liking.

Also see: https://github.com/atom/atom/issues/17486#issuecomment-424140110

Imho you can safely update to Mojave.

**Comment by lee-dohm** [comment]
@timothymarois Please see [the FAQ](https://discuss.atom.io/t/macos-mojave-font-rendering-change/59058)

**Comment by agustinbus** [comment]
@daviwil thanks! Work perfectly!

**Comment by cebor** [comment]
I don’t think it is backported yet, is it?

**Comment by dalDevelo** [comment]
Apparently not 🤦🏻‍♂️

Oh well, at the very least, this has highlighted a big blackspot in my understanding of how GIT works. Back to reading for me 🙄
