### ISSUE TITLE
I cannot quit Atom

### ISSUE THREAD

**Issue by darius-leong** [atom/atom#20831]
I've tried to quit Atom but it hasn't been working.
I'm pretty sure that I've tried everything:
Command + Q
and selecting quit from the dropdown menu.
I'm using a Mac.
If anyone has any solutions, or this problem has been fixed, please tell me.

**Comment by UziTech** [comment]
Have you tried `:q!`? 🤣

Just kidding. It seems like it might be frozen. Are you able to kill it from the task manager?

**Comment by ag-coder** [comment]
same here on osx 10.13.6
have to kill it always whit the task manager!

**Comment by UziTech** [comment]
looks like a duplicate of #17672

**Comment by lra** [comment]
> If anyone has any solutions, or this problem has been fixed, please tell me.

You can use the "Force Quit` entry in the Apple Menu as a workaround.

Like @UziTech said, dupe of #17672

**Comment by dquessenberry** [comment]
I am having the same problem. I believe this issue is caused by a package you have installed. Luckily for me I only have about a half a dozen different packages installed, so it was easy to find what package(s) was the culprit. You can view your installed packages under the Settings View, found under the menu Packages > Settings View > Open. Once opened, click Packages from the left panel to see the list of package you have installed. From the Settings View, you can disable a package, kill the app, re-open Atom, then try quitting. You have to do it one by one until you found the offending package. I recommend starting with any recently installed packages first. Luckily for me it was the most recent package I installed, so it didn't take long for me to find. In my case, it was the "pigments" package. I don't really need that package anyway, so uninstalled it. Good luck!

**Comment by 1oo7** [comment]
Still having this issue. 

@dquessenberry No matter what, there is no kind of package that should be able to prevent Atom from quitting. 

Atom should be updated such that no matter what packages the user has installed, the Quit function always works!!!!

**Comment by dquessenberry** [comment]
> @dquessenberry No matter what, there is no kind of package that should be able to prevent Atom from quitting. 
> 
> 
> 
> Atom should be updated such that no matter what packages the user has installed, the Quit function always works!!!!

I agree with you. Just thought I would share what helped me, at least for a short term fix.

**Comment by joomlabeat** [comment]
I am having the same issue since some weeks... I haven't installed any packaged recently though. Anyway, I do force quit.

**Comment by mciarlo** [comment]
+1 on this issue. I always have to force quit.

**Comment by sakadalim** [comment]
I'm having the same issue as well :/

**Comment by fatihandyildiz** [comment]
same issue! no solutions?

**Comment by dlsoltero** [comment]
Same here, I have to force quit every time, really annoying.

**Comment by mncmncmnc** [comment]
Same here :(
Can't figure it out

**Comment by jeffkimbrel** [comment]
Anyone not even able to force quit? 

There are no atom processes in the activity monitor, which is weird. It does show up in the Force Quit Applications window, but force quit attempts don't do anything. In the dock, there is no white circle indicating the app isn't running, but right-clicking on the app icon has the message "application not responding". Finally, attempts to restart fail, with the OS saying it can't restart because Atom can't be closed. I have to physically shut down via the power button. 

Atom v1.50.0
MacOS Mojave 10.14.6

**Comment by captainsham** [comment]
I can reproduce this issue on my Mac running 10.14.6. The first version of Atom that has this issue for me is 1.47. Maybe the upgrade to Electron 5.0.12 is relevant?

**Comment by egarpor** [comment]
Same issue here with Atom 1.50.0 under Mac 10.15.6.

**Comment by HCLarsen** [comment]
I'm also having this issue. Didn't happen prior to a week ago. No new packages installed, upgraded to Atom 1.50.0, but that didn't fix it.

Force quit works, but when I open it next time, it always opens to the same project, but not the one I was using previously.

**Comment by HCLarsen** [comment]
I was also having this issue. Didn't happen prior to a week ago. No new packages installed, upgraded to Atom 1.50.0, but that didn't fix it. Also just figured out how to get around it, and what it takes to reproduce the issue. 

Whenever I opened Atom, it would open to the same project. Let's called that Project A. If I close that window, leaving no Atom windows open, and then open a different project(Project B), then I can't quit. When I force quit, then reopen atom, it opens with Project A again.

Now, if I open Project B while Project A is still open, and then close Project A, suddenly I can quit normally without issue.

Can anyone else confirm if this works for them too?

**Comment by misterbastean** [comment]
@HCLarsen Can confirm. Open one project (A), can still quit. However, if I close all windows for Project A and open another project (B), I can no longer quit. Have to use Activity Monitor.

If I still have Project A open when I open Project B, I am still able to quit, even if I close all Project A windows first.

**Comment by drinkdecaf** [comment]
Was still experiencing this issue even with all packages disabled. I got so sick of it that I deleted my ~/Library/Application Support/Atom folder entirely, which seems to have at least temporarily fixed the issue, at the cost of loosing my "Reopen Project" history. I checked, and my Themes, Packages, Config etc seem to be intact, which is consistent with my understanding they're stored in ~/.atom 

Not advising this as a fix necessarily, but seems to be working for me at least.

**Comment by therealsaumil** [comment]
@HCLarsen Can confirm. Tested on Atom 1.51.0, macOS 10.13.6 High Sierra

**Comment by startryst** [comment]
Confirmed, Atom 1.51.0, macOS 10.14.6 (18G6032) Mojave

**Comment by mk347** [comment]
I solved the issue by changing the core setting "Restore Previous Windows on Start" to "No".

**Comment by micdonato** [comment]
I have this problem too

**Comment by tbuehl** [comment]
@HCLarsen Yes, seems to be the case for me too

**Comment by TheWeirdDodo** [comment]
Jup, also got this issue on my macbook

**Comment by jeff-hykin** [comment]
This should be a reliable workaround

in your init.coffee add
```
atom.commands.add '*', 'application:delayed-self-murder', (options) ->
    # first try normal quitting
    atom.commands.selectorBasedListenersByCommandName["application:quit"][0].didDispatch()
    waitTime = 500 #half a second
    # after a certain amount of time, murder atom
    setTimeout ->
        process = require("process")
        childProcess =  require("child_process")
        childProcess.exec("kill -9 #{process.ppid}")
    , waitTime
```

in your keymap.cson add
```
'*':
    'cmd-q': 'application:delayed-self-murder'
```

Reload the window (or restart Atom) and now cmd+q should always work (note: unsaved work/undo buffer probably not guaranteed)
If you don't care about unsaved work, you can change the `waitTime = 500` to `waitTime = 0`

**Comment by rjalexa** [comment]
MacOS 10.15.7
Atom 1.52.0

same issue

Atom works well but can killed only by a "Force Quit" from activity monitor.

**Comment by marcocasadio** [comment]
Same for me

MacOS 10.15.7
Atom 1.52.0 x64

I need to force quit to exit

**Comment by fsimonjetz** [comment]
I have the same issue on MacOS 10.15.7 and Atom 1.53.0 and can confirm @HCLarsen except that it doesn't seem to matter if it's the same project. I usually use Atom from the command line, but I can certainly reproduce the issue by doing the following:

1. Click on Atom in the dock -> last project opens
2. Click on the "x" so that Atom remains open w/o any open windows - can still quit by `command + q`
3. Go to "File" -> "Reopen last project"
4. `command + q` closes the window but the app remains open and can only be force-quit

**Comment by epam-ocherniavskaia** [comment]
Same for me

MacOS  10.15.6 
Atom 1.53.0 64

**Comment by Ronnie-J** [comment]
Same for me

MacOS 10.15.6 
Atom x64 1.53.0

**Comment by btangmu** [comment]
Same for me

MacOS 11.0.1
Atom 1.53.0 x64

**Comment by mtoensing** [comment]
Same

**Comment by swinggraphics** [comment]
I have only core packages installed. The inability to quit has come up randomly over about the past year. I don't remember experiencing it before then. Concurrently, it has started being random about weather it quits when all windows have been closed.

**Comment by mpieropan** [comment]
Same problem here, I'm using Atom 1.53.0 x64 on macOS HighSierra 10.13.6. I often need to force quit the application.

**Comment by paulbhartzog-tti** [comment]
Also, when it fails to quit, it can actually prevent shutdown and you can't Force Quit it either.  I have had to physically power off my Mac laptop.  This is not ok.

**Comment by paulbhartzog** [comment]
Also, when it fails to quit, it can actually prevent shutdown and you can't Force Quit it either.  I have had to physically power off my Mac laptop.  This is not ok.

**Comment by halukakin** [comment]
Same problem here. 1.53.0 x64 MacOS, Catalina 10.15.7. 
I have to force quit all the time.

**Comment by smdjeff** [comment]
Same

**Comment by aminya** [comment]
I made a PR that fixes this issue. 
https://github.com/atom/atom/pull/21843

Anyone having this issue can go to this link and request the core maintainers to merge the PR. This would facilitate their review process.

**Comment by cgeyma** [comment]
for my case, whenever i "Reopen Project" a project from project history, atom won't quit normally. have to force quit.
if i use "Open" and select a project from file dialog, atom quits normally.
there is a clear project history selection in "Reopen Project". try clearing that does not help. in fact, the project history is not clearing. that seems to show a problem.
read on the internet to start "atom --clear-window-state"
after that, clearing project history works. all previous project entries are gone.
now, when opening projects, the projects are added back to project history.
with the new project history list, using Reopen Project to open a project does not lead to atom won't quit anymore.
no need to force quit atom anymore

**Comment by lacostenycoder** [comment]
I'm still having this issue on Big Sur when Atom is open and I do a Restart or Shutdown without first shutting down Atom.

**Comment by mtoensing** [comment]
Me too. This is so annoying. No document open in atom. Quit does not work so I always have to force shut down atom. So annoying.

**Comment by aminya** [comment]
Hi folks. The fix for this is included in Atom Nightly _(as of Atom Nightly 1.56.0-nightly1, released on the 8th of January)_, and should be in Atom Beta (1.56) soon. Then Atom stable 1.56.0 some time after that.

(Usually there is about a month or so between new minor releases on each channel).

You can get Atom Nightly here with the fix: https://atom.io/nightly although it's not as stable as Beta or stable releases, and it's possible it might not work so well for a day or two if you leave automatic updates turned on.

_Originally posted by @DeeDeeG in https://github.com/atom/atom/issues/17672#issuecomment-774806049_

**Comment by mgw-sbex** [comment]
Sorry to say this but I'm on 1.58 MacOS Catalina up to date, and I have this problem as well.

**Comment by phoebe-leong** [comment]
its fixed in atom nightly

**Comment by mgw-sbex** [comment]
Sorry I meant 
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

**Comment by ChenTaHung** [comment]
Atom version : 1.60.0
Mac OS : Monterey 12.2.1
Still could not quit Atom with Cmd+Q

**Comment by Cam** [comment]
This issue still exists in the latest version when run in the latest version of MacOS. This issue should be reopened.

**Comment by mtoensing** [comment]
Because of this problem I switch to VS Code. I never looked back. I don’t know why the dev team is ignoring it this tedious bug in Atom while the VS Code team does not have this problem.

**Comment by iamkeir** [comment]
Experiencing this too.
