### ISSUE TITLE
Unable to install on Ubuntu 20.10

### ISSUE THREAD

**Issue by hellocatfood** [atom/atom#21570]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
I've just upgraded to Ubuntu 20.10 and I'm unable to install atom on it. It relies on `gvfs-bin` which is no longer available.

### Steps to Reproduce

1. Download atom.deb
2. run `sudo dpkg -i atom-amd64.deb` to try and install atom

**Expected behavior:**

Atom should install successfully.

**Actual behavior:**

The following error is displayed:
```
Selecting previously unselected package atom.
(Reading database ... 276322 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.52.0) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on gvfs-bin; however:
  Package gvfs-bin is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu4) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 atom
```

**Reproduces how often:**

Every time.

### Versions
I can't install atom so I can't get version number by running a command. On the website it shows version 1.52.0.

### Additional Information

Running `aptitude search gvfs` shows that `gvfs-bin` isn't in Ubuntu's repositories.
```
i A gvfs                            - userspace virtual filesystem - GIO module 
p   gvfs:i386                       - userspace virtual filesystem - GIO module 
i A gvfs-backends                   - userspace virtual filesystem - backends   
p   gvfs-backends:i386              - userspace virtual filesystem - backends   
i A gvfs-common                     - userspace virtual filesystem - common data
v   gvfs-common:i386                -                                           
i A gvfs-daemons                    - userspace virtual filesystem - servers    
p   gvfs-daemons:i386               - userspace virtual filesystem - servers    
i A gvfs-fuse                       - userspace virtual filesystem - fuse server
p   gvfs-fuse:i386                  - userspace virtual filesystem - fuse server
i A gvfs-libs                       - userspace virtual filesystem - private lib
p   gvfs-libs:i386                  - userspace virtual filesystem - private lib
p   xmms2-plugin-gvfs               - XMMS2 - gvfs plug-in      
```

**Comment by mmstick** [comment]
The package can be fixed by declaring the dependency as `gvfs | gvfs-bin`

**Comment by emcee6798** [comment]
> The package can be fixed by declaring the dependency as `gvfs | gvfs-bin`

Can you tell me how? I want to be sure I'll be able to use atom before upgrading to Ubuntu 20.10.

**Comment by mmstick** [comment]
This is on the packager to define

**Comment by bittin** [comment]
Found out the same problems some weeks ago, when i was running 20.10 RC
and got the tip to try to install the latest beta version: https://atom.io/beta https://atom.io/download/deb?channel=beta and that worked better https://github.com/atom/atom/issues/21494 

But yeah might be good if all dependency packages are packaged

**Comment by nergdron** [comment]
do the atom devs not start building packages for new releases before they come out? it's surprising to me this wasn't caught automatically by their CI pipeline.

**Comment by nergdron** [comment]
I thought I'd patch up the `control.in` file to specify this and submit a patch, but their control file doesn't even specify gvfs in any capacity. as well, when I try to install the package, it actually installs, but then fails at the configuration phase. so it's unclear to me what is going on with the packaging and what's even pulling in the `gvfs-bin` requirement. in any case, it needs some fixing up for 20.04.

**Comment by mmstick** [comment]
Yeah it's a little strange that they generate one from JavaScript instead of just maintaining it as a text file like everyone else.

**Comment by sbrl** [comment]
According to #21494, this is fixed in the beta version of Atom.

**Comment by bittin** [comment]
> According to #21494, this is fixed in the beta version of Atom.

Have not tested however as i then i had installed the dependencies, so would be great if someone that has not could test, but according to the Atom devs and some Ubuntu people it should be

**Comment by abraxxa** [comment]
The Atom 1.53.0 beta version works but I'm also wondering why the 1.52.0 version wasn't repackaged or a 1.52.1 release created in the three weeks between the bug report and the release of Ubuntu 20.10.

**Comment by Amazeryogo** [comment]
the 1.53.0 beta is working on Pop!OS 20.10  (which is basically ubuntu 20.10) but 1.52 is still not installable.

**Comment by emcee6798** [comment]
1.53 stable is out fyi
