### ISSUE TITLE
Windows: BufferedNodeProcess doesnt work well 

### ISSUE THREAD

**Issue by oak-tree** [atom/atom#2887]
this function use "atom.exe" instead of "node"  to run node function and therefore fails for example to use linter

buffer-process.js 

```
 module.exports = BufferedNodeProcess = (function(_super) {
   __extends(BufferedNodeProcess, _super); 

function BufferedNodeProcess(_arg) {
  var args, command, exit, node, options, stderr, stdout;
  command = _arg.command, args = _arg.args, options = _arg.options, stdout = _arg.stdout, stderr = _arg.stderr, exit = _arg.exit;
  node = process.platform === 'darwin' ? path.resolve(process.resourcesPath, '..', 'Frameworks', 'Atom Helper.app', 'Contents', 'MacOS', 'Atom Helper') : process.execPath;

}
```

i think that this code should check if process.platfrom === "win32" and if so resolve with "node" and not with process.execPath .

**Comment by park9140** [comment]
@zcbenz,  I'm trying to execute a `BufferedNodeProcess` on windows, and it doesn't seem to work at all.  Even a simple script that doesn't use `stdout` doesn't work.

`script.js`
```
setInterval(function() {
  console.log('interval');
}, 1000)
```

Running this using `atom.exe script.js` with `set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1` will log correctly on the interval.  However, when I run `script.js` via `BufferedNodeProcess` it exits immediately with code 1, and no more information.

Additionally, running `BufferedProcess` and executing `atom.exe` will not execute.

My `atom-typescript-tools` package cannot work without this functionality as I need to boot the secondary process to not block the UI thread.

**Comment by park9140** [comment]
@zcbenz, http://strongloop.com/strongblog/whats-new-node-js-v0-12-multiple-context-execution/, out of curiosity is this going to be available in Atom?  If there is an interface you are working on, I would be glad to act as an alpha tester, sounds like it should be a much easier cross platform experience for what I'm doing.

**Comment by basarat** [comment]
> Even a simple script that doesn't use stdout doesn't work.

I believe `console.log` is still stdout. 

> Error: EBADF, bad file descriptor

This also explains this : https://github.com/travs/atom-package-dependencies/issues/6 FYI all if you run something in `shelljs` you need to run it with `silent` : https://github.com/TypeStrong/atom-typescript/commit/52833e9884abb6df7d895777665b79632fb67ec4

**Comment by park9140** [comment]
@basarat, I also tried the same code without the console.log(), it fails there as well.  I also tried just running `atom.exe -v` which should output the node version.

**Comment by basarat** [comment]
@park9140 I think any form of non-error output even `atom.exe -v` would still go to `process.stdout`

**Comment by park9140** [comment]
@basarat, true however a long running script with continuos timeouts keeping it open would not have output of any sort.  Additionally, running the same tests directly against `atom.exe` in a standard console works fine.

**Comment by basarat** [comment]
> however a long running script with continuos timeouts keeping it open would not have output of any sort.

Yes.

FYI a simple `empty` script also fails on `spawn`:

https://github.com/atom/atom/issues/5000#issuecomment-72409485

**Comment by basarat** [comment]
I definitely get this error on `spawn` but I don't get this manually running it so something weirder is happening 

![image](https://cloud.githubusercontent.com/assets/874898/6052289/278e0cc6-ad25-11e4-8c11-0ce62af1ce77.png)

```shell
C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>set ATOM_SHELL_INTERNAL_RUN_AS_NODE
ATOM_SHELL_INTERNAL_RUN_AS_NODE=1

C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>cat test.js
console.log('hello world');

C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>atom test.js

C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>hello world

C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>
```

**Comment by jonathandelgado** [comment]
I had the same issue with this, doing something like the following fixes it.

```
remote.proc = cp.fork(path, {
	execPath: process.platform === 'win32' ?
		'c:\\PROGRAM FILES\\NODEJS\\node.exe' :
		'/usr/local/bin/node',
	silent: true
});
```

**Comment by basarat** [comment]
What is weird is that I get `C:\Users\basaratsyed\AppData\Local\atom\app-0.177.0>hello world
` instead of just `hello world` and it does not exit untill I press *enter*: 

```
C:\Users\basaratsyed\AppData\Local\atom\app-0.182.0>atom test.js

C:\Users\basaratsyed\AppData\Local\atom\app-0.182.0>hello world  ///  I need to press enter for atom to exit

C:\Users\basaratsyed\AppData\Local\atom\app-0.182.0>node test.js
hello world

C:\Users\basaratsyed\AppData\Local\atom\app-0.182.0>
```

**Comment by basarat** [comment]
@csnover can you try similar commands for a mac. Does it hang after `atom test.js`?

**Comment by basarat** [comment]
Here is a bit more context. Using *atom as a node REPL* behaves weird compared to the standard node REPL. It seems confused about the *prompt*.

![asnode](https://cloud.githubusercontent.com/assets/874898/6341923/bc437dd4-bc24-11e4-84b0-f2e42702d199.gif)

**Comment by csnover** [comment]
```
$ ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 /Application/Atom.app/Contents/Frameworks/Atom\ Helper.app/Contents/MacOS/Atom\ Helper test.js
hello world
```

**Comment by basarat** [comment]
@zcbenz why is conversion done to utf8 *only on windows*: https://github.com/atom/atom-shell/blob/master/atom/app/atom_main.cc#L105-L137 (this is based on my rusty understanding of C)

**Comment by Zoltu** [comment]
I am experiencing the same issue as @basarat.  Executing js with atom requires a press enter to continue.  This is problematic because when I run using `BufferedNodeProcess` the process never ends.  If I look at process explorer I can see the launched atom process just sitting there doing nothing.
![image](https://cloud.githubusercontent.com/assets/886059/7195677/7523ee76-e478-11e4-86ff-a558864e21ae.png)
I suspect because it is waiting for me to hit enter.  On a related note, I am not receiving stderr or stdout callbacks, I suspect this is because the process never ends?

**Comment by basarat** [comment]
FWIW we did manage to spawn properly on both OSes : https://github.com/TypeStrong/atom-typescript/blob/master/lib/worker/lib/workerLib.ts#L170-L183

Important stuff is to not copy `env` and only set one property (`ATOM_SHELL_...`) and set `cwd` correctly: 

```ts
this.child = spawn(process.execPath, [
       childJsPath
    ], { cwd: path.dirname(childJsPath), 
         env: { ATOM_SHELL_INTERNAL_RUN_AS_NODE: '1' }, 
         stdio: ['ipc'] 
        });
```

I arrived at this fix purely but banging my head against it for long enough. `Object.create(process.env)` should work but doesn't.

That said be warned that there are some cases where Atom behaves weird when run like this. e.g. I got a totally reproduceable but nearly impossibly isolatable `ReferenceError` bug : https://github.com/Microsoft/TypeScript/pull/2522#issuecomment-87336165 

YMMV.

Also if you spawn atom on your own package script ... you will run into this as well on windows: https://github.com/TypeStrong/atom-typescript/issues/195

Having these edge cases is why I didn't post this solution here early ... so use with care and :heart:

**Comment by Zoltu** [comment]
Setting the `cwd` manually fixed the not exiting automatically.  Setting the env to something minimal (`ATOM_SHELL_INTERNAL_RUN_AS_NODE` and one other I needed for my project) fixed it not logging anything (it is unclear whether before it was actually doing any work or not).

**Comment by basarat** [comment]
> whether before it was actually doing any work or not

It wasn't. I tried :rose:

**Comment by NicholasGW** [comment]
Seem to still be having problems spawning a node process in Windows with Atom 1.0.19...any new news on this? I tried setting a minimal env to no avail as suggested; process is still exiting with a 1 status immediately.

**Comment by Arcanemagus** [comment]
It looks like this has majorly broken with v1.7.0 on Windows, all of the linters that use BufferedNodeProcess are failing due to no contents being returned to `stdout`.

**Comment by damieng** [comment]
https://github.com/atom/atom/issues/11471 has been fixed making stdout work again. Does this mean this issue is now also addressed?

**Comment by jonathandelgado** [comment]
@damieng No, this issue has to do with how we launch the children processes in general, not the stdout.

**Comment by lee-dohm** [comment]
@jonathandelgado or anyone else, can you give a summary of what is still currently broken? I'm pretty certain this has morphed since it was opened and I would like to get an understanding for what specifically is broken, most likely open a new Issue specifically for that, and then close this.

**Comment by sadovnychyi** [comment]
Looks like .kill() method still does not work properly if Atom wasn't ran from command line:

> So platform is all set and the correct method of BufferedProcess is called, but somehow it fails to > correctly spawn wmic to get the child process ids to kill, despite clearly having it in the PATH.

> However, when I start Atom from MSYS2 everything works - from cmd or the taskbar it exhibits the > behavior above.

Related issues: https://github.com/sadovnychyi/autocomplete-python/issues/202#issuecomment-210792599, https://github.com/sadovnychyi/autocomplete-python/issues/205#issuecomment-217151877

Can ask @mostaphaRoudsari or @maurerv for steps to reproduce.

**Comment by damieng** [comment]
Can we create a new issue for this specific remainder and close this one?  A lot of the other parts covered in this thread appear to have been addressed and I agree with @lee-dohm that we'd need clear steps as to what issues still remain.
