### ISSUE TITLE
Atom has excessive battery impact compared to other apps on Mac OS Yosemite

### ISSUE THREAD

**Issue by AlexYursha** [atom/atom#4019]
Atom's energy impact goes up to 25 points of energy impact with just 4 tabs open when idle. To compare Sublime Text 3 uses just 0.1, Xcode - 0.9 and Intellij IDEA - 8 points when idle. When moving keyboard focus to Intellij IDEA it still uses less power than idle Atom. Thus Yosemite reports Atom as an app using significant energy in system bar.

**Comment by rdlugosz** [comment]
While there may be some "artificial reporting" going on, in general the energy footprint of Chromium is high relative to other browsers running on OS X. For example, spend a little time just doing regular web browsing with Safari and then similar activity with Chrome. You'll notice that your time with Chrome has used a lot more battery than Safari had—even if you aren't hitting sites with a lot of flash, etc.

This bug should probably be closed as "not an Atom bug" unless someone is able to directly show that Atom itself is contributing to resource usage above and beyond what Chromium introduces as a baseline.

**Comment by paulcbetts** [comment]
There are certainly things that Atom could do even at a JavaScript level to improve battery usage. Removing as many persistent timers as possible is high on the list

**Comment by rdlugosz** [comment]
I did a bit of experimenting and would agree—Atom certainly seems to drain battery faster than just browsing in Chrome. In fact, opening just an empty Atom window and minimizing it costs you a constant 4-8% CPU usage. Color me convinced that there's a problem!

**Comment by bitardo** [comment]
Any update on this?
I confirm – *idle* Atom uses *more* than a VMware machine running Windows and about as much as Safari during active browsing. This is a major concern since a lot of us work unplugged.

![screenshot at may 24 11-27-28](https://cloud.githubusercontent.com/assets/12165130/7787204/ff5c197c-0207-11e5-8b16-e55348adbe26.png)

**Comment by mnquintana** [comment]
@bitardo I think you may be misreading that – idle Atom has an energy impact of 0.4 which is pretty negligible, but an average energy impact of 100.62 when in use. Since Atom is built on Chromium it's not surprising that it would have an average energy impact comparable to another WebKit browser.

**Comment by SolomonBier** [comment]
Experiencing same problem-surprising clocking 100+ when idle

**Comment by carlhopf** [comment]
running OS X, atom 1.0:

i'm getting an energy impact of ~11 when idling while window is focused.

using https://atom.io/packages/cursor-blink-interval to set the cursor blink interval to 0 (disabled) the energy impact goes down to ~5 while idling. this is about the same as letting the app sit in background.

**Comment by ssorallen** [comment]
Is it safe to call [`atom.views.stopPollingDocument`](https://github.com/atom/atom/blob/master/src/view-registry.coffee#L213) when the window is blurred? That disables cursor blinking and the frequent `performDocumentPoll` that does work even when the app is in the background.

If you open the Timeline in the debugger, click "Record", and then move Atom to the background for several minutes, you get a timeline filled with stack traces every 400ms from the cursors blinking. It only takes ~0.8ms to run the script, but Chromium also triggers a layer composite afterward that takes another ~0.02ms.

**Comment by mark-hahn** [comment]
> every 400ms from the cursors blinking. It only takes ~0.8ms to run the
script,

Using 0.2% of the cpu shouldn't affect anything.

**Comment by ssorallen** [comment]
@mark-hahn I'm not sure what listeners can be added for the `performDocumentPoll`, but stopping that poll kills the unnecessary cursor blinking like @carlhopf did with the "cursor-blink-interval" package.

**Comment by paulcbetts** [comment]
> Using 0.2% of the cpu shouldn't affect anything.

It's not so much the amount of work, is that the 400ms timer prevents the CPU from going into a low power state (C-states) because it is constantly waking up to service the timer. I'm :+1: on pausing or drastically increasing the interval to `performDocumentPoll` when the window is blurred

**Comment by lee-dohm** [comment]
I agree with @paulcbetts. Letting the CPU and other components sleep is going to be where the power savings is really at.

**Comment by maxbrunsfeld** [comment]
:zap: :bulb: :bullettrain_side:

**Comment by FipFop** [comment]
This is important, what's going on here?

I'm still getting record-high Atom energy impact in Activity Monitor on my MacBook Pro.

**Comment by FipFop** [comment]
Yet again: 
<img width="601" alt="screen shot 2016-05-12 at 2 04 21 pm" src="https://cloud.githubusercontent.com/assets/19272022/15225070/96a0a308-184a-11e6-9601-d8c5379c9a96.png">

**Comment by lee-dohm** [comment]
@ElegantSudo [We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster. If you have a specific problem that you would like addressed with steps to reproduce it, please open a new Issue.

**Comment by paulcbetts** [comment]
@ElegantSudo If you have a number >20, it just means you have high CPU usage from some plugin. You should run with `atom --safe` and if it goes away, you get to figure out which plugin is causing you problems. Good luck!

**Comment by square-li** [comment]
@paulcbetts Yea I tried to run atom with safe mode, the problem is still here. And I noticed when I scroll down the page not even really quickly, atom will use a lot of energy. 
Just like this <img width="691" alt="screen shot 2016-05-13 at 09 58 39" src="https://cloud.githubusercontent.com/assets/11740421/15250144/4a885bf8-18f1-11e6-8b05-2dbbb71e34d8.png">
If you scroll down really quickly, the number of energy impact could be raised to 20k in a quick moment for some reason. 
All those test above are run in safe mode.

**Comment by KokoDonchev** [comment]
Hi, is there any progress on this issue? I have 2 plugins installed and they are both commonly used, can't imagine the problem coming from them
<img width="820" alt="screen shot 2016-06-29 at 08 45 02" src="https://cloud.githubusercontent.com/assets/3798807/16444464/fa663d5c-3dd5-11e6-9184-2c7c4a5e19bf.png">

**Comment by ElegantSudo** [comment]
Atom - let's push for at least some concern.

**Comment by nathansobo** [comment]
It's pretty telling that while Atom is #1 on that list, Chrome is #2. Since Atom is a particularly intense web application based on Chrome, this makes sense. We have and will continue to dedicate resources to improving efficiency of the application, which is the only way to reduce the energy impact. But there's no magic wand we can wave to do this. Upgrading Chrome and improving efficiency of our code will gradually make this better over time.

**Comment by kurucu** [comment]
I made one change to the development environment on my MacBook two weeks ago, and it was to install Atom. I have gone from reliably getting 10 hours of battery life from the laptop (on my daily commute, this matters!) to about 3. At this point in time, I won't be enabling safe mode, but instead going back to my old editor until this is fixed.

It may not be high on the priority list for Atom, but a safe workaround would be helpful, if one could be published.

**Comment by ElegantSudo** [comment]
@nathansobo I get it, feature requests and bug fixes are more interesting to work on. But to be honest with you, users would rather have a few bugs and a great battery than no bugs and a shit battery.

Make all of the excuses you want. Users know; where there's a will there's a way.

**Comment by 50Wliu** [comment]
> It may not be high on the priority list for Atom, but a safe workaround would be helpful, if one could be published.

@kurucu The first thing to try here is to enable safe mode and see if the problem persists.  If you are not able to do that then I suppose there is no "safe workaround".

@ElegantSudo To repeat what @lee-dohm said earlier to you:
If you have a specific problem that you would like addressed with steps to reproduce it, please open a new Issue (and completely fill out the provided issue template).

And have you followed @paulcbetts's suggestion to try safe mode?  If so, did that help?

**Comment by lee-dohm** [comment]
@ElegantSudo We have a [Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) for the Atom project for a reason. I can understand you being frustrated or even upset. Just antagonizing people and ignoring their efforts to help you and work with you constructively however is not acceptable.

**Comment by mdavoodi** [comment]
Not sure why this is closed, it's still a problem! Love Atom, would hate to switch to another editor because of battery use.

**Comment by 50Wliu** [comment]
@mdavoodi could you please open a new issue and fill out the issue template?  That would help us a lot!

**Comment by syedrakib** [comment]
Why is this issue closed while it's still a major issue?

**Comment by 50Wliu** [comment]
The leading cause of this issue was fixed, which is why we closed it.  Leaving it open would only lead to a generalization of the issue, which in most cases makes it unactionable.  If you are still experiencing battery consumption problems please open a new issue so we can investigate your specific case further.
