### ISSUE TITLE
Request for package information failed: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by HarryLikesCode** [atom/atom#5148]
Hello, 
this could possibly be related to #2372. Here is the exact error message: 
`Request for package information failed: getaddrinfo ENOTFOUND`. The output from `script/build` is included below.

```sh
[harry@harry-laptop atom]$ script/build
Node: v0.10.35
npm: v2.1.18
Installing build modules...
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.10.35","npm":"2.1.18"})
Installing apm...
npm ERR! fetch failed https://registry.npmjs.org/read/-/read-1.0.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/read/-/read-1.0.5.tgz
../src/keytar_posix.cc: In function ‘bool keytar::AddPassword(const string&, const string&, const string&)’:
../src/keytar_posix.cc:23:31: warning: ‘GnomeKeyringResult gnome_keyring_store_password_sync(const GnomeKeyringPasswordSchema*, const gchar*, const gchar*, const gchar*, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:483): Use 'secret_password_store_sync' instead [-Wdeprecated-declarations]
   GnomeKeyringResult result = gnome_keyring_store_password_sync(
                               ^
../src/keytar_posix.cc:30:11: warning: ‘GnomeKeyringResult gnome_keyring_store_password_sync(const GnomeKeyringPasswordSchema*, const gchar*, const gchar*, const gchar*, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:483): Use 'secret_password_store_sync' instead [-Wdeprecated-declarations]
       NULL);
           ^
../src/keytar_posix.cc: In function ‘bool keytar::GetPassword(const string&, const string&, std::string*)’:
../src/keytar_posix.cc:38:31: warning: ‘GnomeKeyringResult gnome_keyring_find_password_sync(const GnomeKeyringPasswordSchema*, gchar**, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:497): Use 'secret_password_lookup_sync' instead [-Wdeprecated-declarations]
   GnomeKeyringResult result = gnome_keyring_find_password_sync(
                               ^
../src/keytar_posix.cc:43:11: warning: ‘GnomeKeyringResult gnome_keyring_find_password_sync(const GnomeKeyringPasswordSchema*, gchar**, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:497): Use 'secret_password_lookup_sync' instead [-Wdeprecated-declarations]
       NULL);
           ^
../src/keytar_posix.cc:49:3: warning: ‘void gnome_keyring_free_password(gchar*)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:513): Use 'secret_password_free' instead [-Wdeprecated-declarations]
   gnome_keyring_free_password(raw_passwords);
   ^
../src/keytar_posix.cc:49:44: warning: ‘void gnome_keyring_free_password(gchar*)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:513): Use 'secret_password_free' instead [-Wdeprecated-declarations]
   gnome_keyring_free_password(raw_passwords);
                                            ^
../src/keytar_posix.cc: In function ‘bool keytar::DeletePassword(const string&, const string&)’:
../src/keytar_posix.cc:54:10: warning: ‘GnomeKeyringResult gnome_keyring_delete_password_sync(const GnomeKeyringPasswordSchema*, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:509): Use 'secret_password_clear_sync' instead [-Wdeprecated-declarations]
   return gnome_keyring_delete_password_sync(
          ^
../src/keytar_posix.cc:58:11: warning: ‘GnomeKeyringResult gnome_keyring_delete_password_sync(const GnomeKeyringPasswordSchema*, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:509): Use 'secret_password_clear_sync' instead [-Wdeprecated-declarations]
       NULL) == GNOME_KEYRING_RESULT_OK;
           ^
../src/keytar_posix.cc: In function ‘bool keytar::FindPassword(const string&, std::string*)’:
../src/keytar_posix.cc:63:31: warning: ‘GnomeKeyringResult gnome_keyring_find_password_sync(const GnomeKeyringPasswordSchema*, gchar**, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:497): Use 'secret_password_lookup_sync' instead [-Wdeprecated-declarations]
   GnomeKeyringResult result = gnome_keyring_find_password_sync(
                               ^
../src/keytar_posix.cc:67:11: warning: ‘GnomeKeyringResult gnome_keyring_find_password_sync(const GnomeKeyringPasswordSchema*, gchar**, ...)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:497): Use 'secret_password_lookup_sync' instead [-Wdeprecated-declarations]
       NULL);
           ^
../src/keytar_posix.cc:73:3: warning: ‘void gnome_keyring_free_password(gchar*)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:513): Use 'secret_password_free' instead [-Wdeprecated-declarations]
   gnome_keyring_free_password(raw_passwords);
   ^
../src/keytar_posix.cc:73:44: warning: ‘void gnome_keyring_free_password(gchar*)’ is deprecated (declared at /usr/include/gnome-keyring-1/gnome-keyring.h:513): Use 'secret_password_free' instead [-Wdeprecated-declarations]
   gnome_keyring_free_password(raw_passwords);
                                            ^
Installing modules ✓
Installing atom-dark-syntax@0.26.0 ✗
Request for package information failed: getaddrinfo ENOTFOUND
```

Attempting to keep going (keep calling `script/build`) results in this:

```sh
[harry@harry-laptop atom]$ script/build
Node: v0.10.35
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Installing atom-dark-syntax@0.26.0 ✓
Installing atom-dark-ui@0.46.0 ✓
Installing atom-light-syntax@0.26.0 ✓
Installing atom-light-ui@0.40.0 ✓
Installing base16-tomorrow-dark-theme@0.25.0 ✓
Installing base16-tomorrow-light-theme@0.8.0 ✓
Installing solarized-dark-syntax@0.32.0 ✓
Installing solarized-light-syntax@0.19.0 ✓
Installing archive-view@0.44.0 ✓
Installing autocomplete@0.43.0 ✓
Installing autoflow@0.21.0 ✓
Installing autosave@0.20.0 ✗
Unable to download https://www.atom.io/api/packages/autosave/versions/0.20.0/tarball: getaddrinfo ENOTFOUND
```

To check if it was possibly an issue with the website that needed to be reached, I manually went to the link in my web browser. This results in a popup asking me if I'd like to download the tarball so I don't think it's an issue with a proxy or anything (I have no proxy or special internet setups).

This is affecting: Manjaro Ascella (0.8.11) 64-bit. Any help is much appreciated as this is my day-to-day editor.

### Edit
The version affected is v0.174.0 I believe. It was cloned from the main repository just a few minutes ago.

**Comment by ram-you** [comment]
Hi, the v0.178.0 (on Linux Mint) is affected too, same problem when trying to install new package : <strong> getaddrinfo ENOTFOUND</strong>

**Comment by IcyTesseract** [comment]
Did you build it or use a `.deb` file? No problems with the `.rpm` on Fedora 21 x64 or building it on Arch x64.

**Comment by ram-you** [comment]
I'm using the the downloaded .deb.

**Comment by kevinsawicki** [comment]
I think this issue has been resolved since it looks like an intermittent connectivity issue that has not been recently reporting, closing this out.

**Comment by mamoit** [comment]
I'm consistently getting this error.
Running ubuntu 15.04 and installed the `deb` file.

**Comment by richin13** [comment]
![captura de pantalla de 2016-04-13 10-03-14](https://cloud.githubusercontent.com/assets/8370058/14500369/02838ec6-015f-11e6-9053-4245206640b7.png)
This affected me today

**Comment by okram999** [comment]
I know the issue is closed, but the issue still exist 

**C:\Users\XXXXX\AppData\Local\atom\bin>apm install language-groovy
Installing language-groovy to C:\Users\XXXXX\.atom\packages failed
Request for package information failed: getaddrinfo ENOTFOUND (ENOTFOUND)**

is there a way to install packages, offline?

**Comment by jkw** [comment]
To solve this issue, flush your DNS. That helped me.

**Comment by ed-torvalds** [comment]
Yup, flushing your DNS or reconnecting to your network works!

**Comment by Azhar2k16** [comment]
@jkw Yep worked for me as well. Thanks 
Was wondering how did you figure it out :)

**Comment by matanster** [comment]
Is this still an issue? others haven't posted the full error, in my case it is the following:
```
Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:443
```

**Comment by Arcanemagus** [comment]
@matanster `ENOTFOUND` errors like that are DNS resolution failures. Since Atom is still definitely using `atom.io`, the problem you are seeing is somewhere in your local DNS resolution. Try the troubleshooting steps above to see if that resolves your problem but the issue isn't on Atom's end 😉.

**Comment by matanster** [comment]
Got it! sorry for the bother. 
Noting also that this may transiently occur, given whatever DNS infrastructure between oneself and atom.io.
