### ISSUE TITLE
Smooth scrolling (Linux)

### ISSUE THREAD

**Issue by oktayacikalin** [atom/atom#5359]
I've seen some work in improving the smoothness of scrolling so far. But I'm wondering if it's actually possible to get real smooth scrolling or at least if it's planned for the near future?
Just reducing the scroll sensitivity to 1 line at a time is not a real solution...

**Comment by benogle** [comment]
@nathansobo will be soon working on new rendering techniques that will hopefully speed up typing and scrolling performance, which should make things smoother.

**Comment by theblacklion** [comment]
Awesome to hear that :)

**Comment by Ehsanizadi** [comment]
When do you expect smooth scrolling to be added to atom text editor?

**Comment by Tenrys** [comment]
For now, put this in your style sheet:
    atom-text-editor::shadow .editor--private .tile {
        transition: -webkit-transform .05s ease-out; // customize the duration.
    }
Courtesy of @Lixquid.

**Comment by UltCombo** [comment]
Looks like @Tenrys's selector no longer works, so I've modified it:

```css
atom-text-editor::shadow .scroll-view > .lines > div > div:not(.cursor) {
  transition: -webkit-transform .1s linear;
}
```

This is still an ugly hack, and does not work very well when scrolling up.

Chrome has a smooth scroll flag under `chrome://flags/#enable-smooth-scrolling`, I wonder if this flag can be enabled in Electron? If so, Atom could add a setting to enable this flag.

**Comment by ebkalderon** [comment]
Thanks for the information, @UltCombo. Any word on when smooth scrolling will work natively?

**Comment by groovy354** [comment]
:+1:  I'd love to see that implemented, as well :)

**Comment by thedaniel** [comment]
@zcbenz any comments on the Chrome smooth scroll flag and whether it's available / relevant in Electron?

**Comment by halohalospecial** [comment]
Would this suffice as a temporary solution?

https://atom.io/packages/animated-page-scroll

**Comment by ArniPL** [comment]
Is this still in the works? I'd love Atom to do smooth scrolling like Sublime does. That CSS hack just isn't cutting it. Thanks! :)

**Comment by alvarolm** [comment]
interested as well, btw that css hack doesnt seems to be working on 1.7 beta 5

**Comment by alvarolm** [comment]
https://github.com/atom/atom/issues/10276

**Comment by kevinrambaud** [comment]
Bump, same thing on OS X El Captain, it's the only feature I miss from Sublime text, the current Atom scroll attacks my eyes 😁

**Comment by TheBrenny** [comment]
@UltCombo, Getting that lovely MS Word feel when you include the cursor though!

```
atom-text-editor::shadow {
  .scroll-view > .lines > div > div {
    transition: -webkit-transform 0.05s linear;
  }
}
```

**Comment by pratyushbarik** [comment]
Upgrade to 1.9. It's using Electron 0.37. I can confirm this resolves the smooth scrolling issue on Ubuntu 14.04.

**Comment by 50Wliu** [comment]
Thanks for the update @pratyushbarik!  If someone can still reproduce this on Atom 1.9.0 please comment here.

**Comment by UltCombo** [comment]
@50Wliu The issue is still reproducible on OS X when using a non-Apple mouse (any mouse with a real scroll wheel instead of touch scrolling).

In any case, I believe this is a Chromium/Blink issue as the same choppy scrolling also happens on Chrome for Mac when using a mouse with scroll wheel.

**Comment by alexandernst** [comment]
I'm with @UltCombo . This isn't fixed.

**Comment by UltCombo** [comment]
I'll reinforce this is only a problem when using a mouse with scroll wheel on a Mac. The smooth scrolling has been working since forever when using pointing devices with touch scrolling, such as the MacBook's touchpad, a Magic Trackpad or Magic Mouse.

Please star [this Blink issue](https://bugs.chromium.org/p/chromium/issues/detail?id=574283) if you'd like Blink (and therefore Electron) to have smooth scrolling for mouse wheel on Mac.

**Comment by jonas-schievink** [comment]
Also still an issue on Linux (x86-64 Arch Linux, X11, Atom 1.9.0) using a regular mouse

**Comment by luco** [comment]
+1

**Comment by Menci** [comment]
@UltCombo How to apply that to line numbers? Thanks.

**Comment by Menci** [comment]
@UltCombo How to apply that to line numbers? Thanks.

**Comment by UltCombo** [comment]
I've pretty much gave up on the CSS hacks already; Setting Atom's scroll sensitivity to `10` provides a decent experience for me at least.

**Comment by alvarolm** [comment]
the css hacks wont work, see http://blog.atom.io/2015/06/24/rendering-improvements.html
unless theres a way to start rendering before starts and keep rendered after ends

**Comment by alvarolm** [comment]
https://github.com/atom/atom/blob/master/src/scrollbar-component.coffee

**Comment by alvarolm** [comment]
here's what happens https://www.youtube.com/watch?v=_S71atc3vQE

**Comment by alvarolm** [comment]
![rendering]
(https://cloud.githubusercontent.com/assets/482957/8293801/3894b004-1938-11e5-9ed8-f6a50022222e.gif)

**Comment by hemedani** [comment]
Please notice [this Add-on](https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb?hl=en) for chrome smooth scroll and [this add-on](https://addons.mozilla.org/en-US/firefox/addon/yet-another-smooth-scrolling/) for Firefox.
Please be sure to add that options for smooth scrolling in Atom.
tnx

**Comment by damianmoore** [comment]
There are several different parts that contribute to a smooth scroll effect but the biggest thing from my perspective (being a touchpad user) is making use of XInput 2.1 events. This is often referred to as "pixel-perfect" scrolling.

With traditional mouse wheels the you cannot scroll an arbitrary amount - the wheel physically settles into a resting position at fixed angles causing button presses 4 & 5 to be triggered which all applications can handle. With a touchpad (or I assume rarer types of fee flowing mouse wheel) scrolling can happen even for just a tiny distance (equivalent to a pixel or two). XInput had to be enhanced to pass through these new types of events.

I've been trying to get all the applications I commonly use to handle this and Atom is the only one left for me. Native GTK3 applications handle it by default, Firefox requires setting an environment variable https://support.mozilla.org/en-US/questions/1091627 and Chromium introduced it recently in version 54 https://bugs.chromium.org/p/chromium/issues/detail?id=384970

Given that Atom is based on Electron, which is in turn based on Chromium, I think smooth scrolling will be enabled when Electron updates the version of Chromium it uses to 54 and then Atom upgrades to this version of Electron. Not sure how long that will take but is see there is at least a branch called 'chrome54' which has been pushed to today: https://github.com/electron/electron/compare/chrome54

**Comment by UltCombo** [comment]
@damianmoore Just to make sure: you are talking about touchpad on Linux specifically, right?

For scroll wheel users, I believe the problem will **not** be fixed by any Chromium/Electron update.

Atom on Windows already uses an Electron version with mouse wheel smooth scrolling enabled, you can see that the Settings view will have a nice smooth scroll. However, the editor view still **does not** have smooth scrolling. I believe that's because Atom's ScrollView intercepts and reimplements scrolling in order to only render the content currently displayed in the viewport.

**Comment by damianmoore** [comment]
@UltCombo Touchpads mainly, yes, but also mouse wheels that move freely rather that locking into discrete positions. Those are probably rare though and I don't have one to test.

I gather that for you (using a standard mouse scroll wheel) smooth scrolling would be implemented by adding animation frames for 100ms or so as the view changes from one position to another. This may help eyes to follow the scroll better but I believe it is not a good enough solution for touchpad users.

I don't know enough details about the implementation of scrolling code in Atom but it seems you're right about the implementation not using standard Chromium/Electron scrolling. In my Atom settings on Linux I can also see that there is animation between scroll positions (but not "pixel-perfect" scrolling). I am now under the impression that when Atom gets updated to Electron based on Chromium v54, the settings view will get "pixel-perfect" scrolling for devices that support XInput 2.1 but it will not benefit the main code view.

I guess all of this will need to be re-implemented in Atom's non-standard code scroll view. I'd assume adding animation between scroll positions will be the easiest to implement first but pixel-perfect scrolling being kept in mind for after.

**Comment by alexandernst** [comment]
I don't understand how XInput has anything to do with this bug. Sublime has smooth scrolling on Linux and it doesn't depend on XInput 2.1 and whatnot.

**Comment by damianmoore** [comment]
@alexandernst There are different types of smooth scrolling:

- The first (and simpler) type of smooth scrolling is when animation is added between the scroll view being in two positions. Scroll events are just button presses. Most mice will do and so do touchpads for applications that don't support the second type.
- The second type allows much more fine-grained scrolling. You can literally scroll by just one or two pixels in apps that support XInput 2.1. This gives a much more responsive feel - similar to how scrolling feels when you use a smartphone or tablet. Mac OS users are very familiar with this. Example: https://youtu.be/IF475wLGYdM?t=57s

**Comment by ilyahoilik** [comment]
@Menci this code works with pagination:

```css
atom-text-editor.editor {
	.scroll-view > .lines > div:not( .cursors ) > div,
	.gutter-container > div > div > div {
		transition: -webkit-transform 0.09s linear;
	}
}
```

But the bug described above is still present, unfortunately. And I don't know easy way to fix it.

**Comment by ffxsam** [comment]
Any updates/progress on this?

**Comment by damianmoore** [comment]
I just upgraded to v1.19 and can confirm proper smooth scrolling is working for my touchpad 💯. Presumably because of the upgrade of Electron to a version that supports XInput 2.1.

If others can confirm the same then I guess this issue is resolved.

**Comment by 50Wliu** [comment]
Thanks for giving us an update @damianmoore.  However, I'll be a bit more careful this time and wait for more reports of smooth scrolling working before closing this issue again.

**Comment by ConsoleTVs** [comment]
Atom 1.19 - Stylesheet

```css
atom-text-editor.editor > div > .scroll-view > div,
atom-text-editor.editor > div > .gutter-container > div {
    transition: -webkit-transform .15s ease;
}
```

**Comment by hagrid67** [comment]
Hi ConsoleTVs - would you be able to suggest how to increase the scroll speed please?  Can it be made to accelerate?   

I'm using a Microsoft Comfort Mouse 4500 on Ubuntu 16.04 (long-time windows user switching to Linux).  I'm looking for an editor with smooth scrolling; VS Code and Eclipse are not currently doing it.   This mouse doesn't have a physical clicky scrolling like many - the position of the wheel is analog not discrete - but I think it only generates events on discrete angles.  (At least, once it gets through the various drivers)

I'm getting nice smooth wheel scrolling in the Atom Settings pages etc; the text editor windows are not doing it by default, but adding ConsoleTVs' stylesheet fix above helped: it scrolls smoothly, just too slowly.  Now I would like to amplify the scrolling a bit, or better, to have accelerating scrolling  (Chrome does this using the Chromium Wheel Smooth Scroller). 

Any ideas?

Many thanks


Atom 1.19.5 x64.

jwpc12:~/Downloads$ xinput list-props 10
Device 'Microsoft Microsoft® Comfort Mouse 4500':
	Device Enabled (136):	1
	Coordinate Transformation Matrix (138):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	Device Accel Profile (265):	0
	Device Accel Constant Deceleration (266):	1.000000
	Device Accel Adaptive Deceleration (267):	1.000000
	Device Accel Velocity Scaling (268):	5.000000
	Device Product ID (256):	1118, 1900
	Device Node (257):	"/dev/input/event6"
	Evdev Axis Inversion (269):	0, 0
	Evdev Axes Swap (271):	0
	Axis Labels (272):	"Rel X" (146), "Rel Y" (147), "Rel Horiz Wheel" (263), "Rel Vert Wheel" (264)
	Button Labels (273):	"Button Left" (139), "Button Middle" (140), "Button Right" (141), "Button Wheel Up" (142), "Button Wheel Down" (143), "Button Horiz Wheel Left" (144), "Button Horiz Wheel Right" (145), "Button Side" (261), "Button Extra" (262), "Button Unknown" (259), "Button Unknown" (259), "Button Unknown" (259), "Button Unknown" (259)
	Evdev Scrolling Distance (274):	1, 1, 1
	Evdev Middle Button Emulation (275):	0
	Evdev Middle Button Timeout (276):	50
	Evdev Middle Button Button (277):	2
	Evdev Third Button Emulation (278):	0
	Evdev Third Button Emulation Timeout (279):	1000
	Evdev Third Button Emulation Button (280):	3
	Evdev Third Button Emulation Threshold (281):	20
	Evdev Wheel Emulation (282):	0
	Evdev Wheel Emulation Axes (283):	0, 0, 4, 5
	Evdev Wheel Emulation Inertia (284):	10
	Evdev Wheel Emulation Timeout (285):	200
	Evdev Wheel Emulation Button (286):	4
	Evdev Drag Lock Buttons (287):	0

**Comment by ConsoleTVs** [comment]
You may decreese the numer .15 to make it faster or change ease to linear for example

**Comment by hagrid67** [comment]
Hey thanks ConsoleTVs;

These seem to just change the timing of the scroll-increment, but the size of the increment stays the same.  I seem to be getting a single pixel per mouse-wheel scroll event.  By default using xinput (1 1 1) I get 7 events per mouse-wheel event, which is 7 lines in other editors, but seems to be 7 pixels in atom right now, ie barely a single line.  I can only adjust this down in xinput (7 1 1 gives a single pixel, completely useless :) )

I've had a quick google for webkit transition etc but I'm not  familiar with CSS.

If I go back to an empty styles.less, I still seem to get the same one-pixel-per-event, but now it's not smooth. 

Might there be a way to tell electron / whatever to scale them up?  (Or even better, accelerate...)

Many thanks.

**Comment by hagrid67** [comment]
May I also ask if you use Atom on Linux - can you recommend a mouse?   These cheap ~$15 mice have been fine for me on Windows but happy to trade up to a touchpad mouse if this works better here.  Sorry to bend the topic somewhat.

**Comment by ConsoleTVs** [comment]
Scroll speed can't be controlled using css. This is something controlled by your mouse drivers. I use linux on my laptop without any mouses. In windows I use a razer mouse and windows is able to change the lines / scroll. I guess this feature is also available in xinput. 

However atom already have soemthing called scroll sensitivity. Check the atom settings, on the editor tab and look for this:

![image](https://user-images.githubusercontent.com/6124435/30063485-24dbc970-924f-11e7-8084-11fd947933f9.png)

**Comment by hagrid67** [comment]
Great - that seems to do it.  (Sorry this is also the first time I've tried atom, I should have found that myself.)
Yes Linux / Xorg seems a bit behind windows in mouse-wheel configuration.  Trying to use it seriously has made it more of an issue for me.
Thanks again.

**Comment by ConsoleTVs** [comment]
You're welcome :)

**Comment by lucaspar** [comment]
Here's the setting I'm using. It smooths the scrolling and eases a little bit the cursor movements, but not at the same rate, so it doesn't become too slow when typing fast.

```less
atom-text-editor::shadow {

    .scroll-view > .lines > div {

        div.cursor {
            transition: -webkit-transform 0.04s ease-out;
        }

        div:not(.cursor) {
            transition: -webkit-transform .15s ease;
        }
        
    }

}
```

**Comment by nathansobo** [comment]
![screen shot 2017-10-27 at 5 53 26 pm](https://user-images.githubusercontent.com/1789/32128957-c4b49184-bb3f-11e7-8989-6b3b9b50aaee.png)

Investigated the scrolling experience this afternoon on Linux a bit. Our problems seem to stem from the fact that, at least on my virtual machine, the `deltaY` of scroll events is always the same no matter how fast I am scrolling. On macOS, that value varies based on my interaction with the touchpad.

I can imagine a solution in which we faked smooth scrolling by taking each wheel event as an acceleration to a velocity that also degrades with friction over several frames. My concern with that is it might not match the behavior of other applications and expectations of all users. This is very unknown territory for me.

**Comment by damianmoore** [comment]
@nathansobo I don't think you need to worry. There has been a lot of confusion in this thread with people discussing adding transitions to fake smooth scrolling between steps. It's hard to find the right terminology to discuss these movements and I assume quite a few people here are not used to using touchpads.

I can confirm that with recent Linux distributions and touchpads the smooth motion works correctly in Atom, the same as with other more native apps (since my post on 9th August). I think this is inherited behaviour from the Chromium project (using XInput2) which has had it properly implemented for about a year. See my previous posts for my understanding on this.

What I guess is happening for you is that your virtual machine software is not translating your MacOS smooth scroll events into Linux's XInput2 smooth scroll events. Instead I guess it falls back to the lowest common denominator and sends those less frequent up/down events to Linux instead. If you try running Linux natively I think you will find the scrolling smooth and the same as native MacOS apps.

One thing I have not had a chance to test yet is whether this behaviour still works under Wayland display server which is now the default in the latest version of Ubuntu. I should get around to trying that in the next week.

**Comment by Ben3eeE** [comment]
@damianmoore Thank you for this information this is really helpful to us 🙇 We have had a lot of recent reports in various issues about smooth scrolling, inertial scrolling and other things being wrong with the scrolling experience on Linux.

**Comment by alexandernst** [comment]
@damianmoore You mention that this has been fixed `with recent Linux distributions and touchpads`, but does smooth scrolling work with regular mouses? IMHO that is what people are complaining about.

**Comment by Ben3eeE** [comment]
Smooth scrolling with a regular mouse doesn't work on Windows for me.

**Comment by damianmoore** [comment]
@alexandernst I was replying to @nathansobo which was about touchpads - "On macOS, that value varies based on my interaction with the touchpad". I can't say what happens with regular mice as I don't have one to test with (they give me wrist pain). I think there will always be complaints with regular mice not appearing smooth as there's lots of faking and animating to do when the wheel just doesn't have anywhere near the resolution. I was more interested in getting the continuous positioning stream of event data through to Atom so that the content moves according to your exact finger position.

**Comment by ssfrr** [comment]
I'm using Atom 1.32.0-beta1 on Linux and not seeing the precision scrolling behavior. As @damianmoore mentioned above this is a separate issue from "smooth" scrolling by adding animation between the discrete steps (and TBH it makes it confusing that these two things are conflated). It seems that the scroll window moves only in increments of about 2 lines. Is there some setting that needs to be enabled?

I'm using Gnome Shell (Wayland).

**Comment by ariasuni** [comment]
Just to sum the situation up:

When using a mouse wheel, the scrolling is not smooth: the view jumps immediately without animation, unlike settings or project view for example.

(I personally don’t have any problem with pixel-perfect touchpad scrolling)

If I understand correctly, it’s a matter of adding an animation but it’s not that simple because of the editor view performance tricks.

**Comment by AlexWayfer** [comment]
> Verify that you can still reproduce the issue in the latest version of Atom

Yes.

> What version of Atom you reproduced the issue on

`1.42.0`

> What OS and version you reproduced the issue on

Arch Linux.

> What steps you followed to reproduce the issue

Scroll via mouse wheel.

**Comment by AlexWayfer** [comment]
The same as earlier, Atom is `1.53.0` now.

**Comment by alerque** [comment]
I believe this issue is completely obsolete and can be closed. Smooth scrolling seems to work fine for me (about 10 increments per line). Using Xorg / Arch Linux packages (1.61.0beta0 and Electron 11).
