### ISSUE TITLE
Editor freezes after a huge paste 

### ISSUE THREAD

**Issue by vickydasta** [atom/atom#5411]
it's freeze,after i was paste some text (it's 79000's),i wish atom can handle 79898 lines of text from paste method.

**Comment by mnquintana** [comment]
This seems potentially related to #307?

**Comment by prabackar** [comment]
I have freeze issue ever for 1987 lines of json object

**Comment by nathansobo** [comment]
My presenter change recently made this problem worse. @maxbrunsfeld you were right, we need a benchmark suite.

**Comment by vickydasta** [comment]
@nathansobo so sorry,yet check if related issue has been posted before
but it's seems to be atom's most critical issue

**Comment by nathansobo** [comment]
It will be fixed on the next release. I agree it was bad.

**Comment by chrisgonzalez** [comment]
@nathansobo I've got a vendor-supplied 131kb html file that is locking up when I try to type anywhere in the doc. Also locks up Atom when opening the file. Is this related?

**Comment by nathansobo** [comment]
@chrisgonzalez Is this a new slowness or has it always been bad? I imagine the latter. We still need to optimize a bunch of intermediate structures between the screen and the buffer before this kind of situation will be tolerable. This is part of my focus over the next few months.

**Comment by vickydasta** [comment]
and,is atom has conflict with some apps ? like idle ? or am i the only one who face this problem before ?

**Comment by vickydasta** [comment]
so sorry if my question has no correlation with our topic

**Comment by nathansobo** [comment]
@vickydasta Not sure I understand your question...

**Comment by vickydasta** [comment]
@nathansobo when i run python-idle & Atom in the same time,after a while,idle freezes,any idea ?

**Comment by chrisgonzalez** [comment]
@nathansobo Not sure as this is a new file, new project. Thanks for focusing on this!

**Comment by nathansobo** [comment]
@chrisgonzalez This should be resolved in `>=0.180.0`. Please let us know if you have further problems.

**Comment by telkomsel666** [comment]
#1

**Comment by telkomsel666** [comment]
#1

**Comment by OmgImAlexis** [comment]
I'm running ``0.205.0`` and I'm still getting crashes with large pastes(<15,000 characters).
I can sometimes just leave it for a few minutes and hope it recovers but most of them time it just kills itself and I have to reopen it.

**Comment by mnquintana** [comment]
@OmgImAlexis Can you try upgrading to 0.208.0?

**Comment by OmgImAlexis** [comment]
@mnquintana doing that now.

**Comment by OmgImAlexis** [comment]
In empty documents it seems perfect now and in documents that already contain some text it doesn't crash but it does stop responding and allow me to either ``Keep Waiting`` or ``Close``.

I'm on OSX 10.10.3 with 4GB of RAM if that makes a difference. I noticed on my Windows 8.1 machine with 24GB of RAM it still sometimes happens but usually I only get issues over 50,000 characters on there.

**Comment by mnquintana** [comment]
@OmgImAlexis Actually now that I look at it, this is a duplicate of https://github.com/atom/atom/issues/979, which is still being worked on.

**Comment by OmgImAlexis** [comment]
Alright, guess this can be locked then.

**Comment by nathansobo** [comment]
We still need a general strategy for deferring computation on paste. The strategy I put in place deals well with loading files we know are large initially, but this is still a hole. We definitely have a plan, but just haven't been able to implement it just yet.

**Comment by Slater-Victoroff** [comment]
Getting this with pretty small text snippets. Currently getting a total freeze with just a ~600 line html file that's even properly formatted.

**Comment by nathansobo** [comment]
Can you reproduce the freeze in safe mode? Freezing with content of that size in the default configuration sounds unlikel.

**Comment by edencorbin** [comment]
I get this on multiple computers/version, say I paste jquery min in atom, https://code.jquery.com/jquery-3.1.1.min.js, it feezes it. It doesn't have an issue if I instead save the file within a folder and look at the file.

**Comment by jp26jp** [comment]
@edencorbin I had the same issue but the Atom beta3 update fixed the issue.

**Comment by Andrewmperryman** [comment]
Hello I'm a newbie to these parts,
I have the similar problem as @edencorbin I'm using Atom v 1.14.3 on a Mac (Mac details below)
This only happen when I copy data from another source & past the content into a new unnamed tab to save, like the contents of a css file for example a bootstrap.min or similar JS file. Please note the data is only say 200kb in size, then Atom just locks up. Otherwise the same existing original file / files can be viewed without any issue if opened by Atom normally.

I use this excellent product in conjunction with Pinegrow..

macOS Sierra 10.12.3
Intel Core i5
2.66 GHz
L2 Cache (per Core): 256 K
L3 Cache: 8 MB
Memory: 4 GB

**Comment by adbejpauli** [comment]
+1 using Atom 1.14.3 on OS X Sierra with 16Gb of Ram I paste a few hundred lines of json and the editor stops responding every time.
