### ISSUE TITLE
Atom installation and update error on Windows

### ISSUE THREAD

**Issue by equinusocio** [atom/atom#5767]
Hi all,
when i try to install Atom on my Windows 8.1 machine i get this error. 

![Error](http://i.imgur.com/nVPa5kw.png)

    
## And the log say:

    Program: Starting Squirrel Updater: --install .
    Program: Starting install, writing to C:\Users\Mattia\AppData\Local\SquirrelTemp
    CheckForUpdateImpl: Reading RELEASES file from C:\Users\Mattia\AppData\Local\SquirrelTemp
    ApplyReleasesImpl: No release to install, running the app
    ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Mattia\AppData\Local\atom\app-0.179.0\atom.exe]
    Program: Starting Squirrel Updater: --install .
    Program: Starting install, writing to C:\Users\Mattia\AppData\Local\SquirrelTemp
    CheckForUpdateImpl: Reading RELEASES file from C:\Users\Mattia\AppData\Local\SquirrelTemp
    ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\Mattia\AppData\Local\atom\app-0.182.0
    ApplyReleasesImpl: Writing files to app directory: C:\Users\Mattia\AppData\Local\atom\app-0.182.0
    IEnableLogger: Failed to update local releases file: System.IO.IOException: File esistente.
    
       in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       in System.IO.__Error.WinIOError()
       in System.IO.Path.InternalGetTempFileName(Boolean checkHost)
       in Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
       in Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ed()
       in System.Threading.Tasks.Task`1.InnerInvoke()
       in System.Threading.Tasks.Task.Execute()
    --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
       in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       in Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>d__ee.MoveNext()
    --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
       in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       in Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()

After this error, i've found the full Atom app (0.182.0) inside the folder AppData\Local\atom\app-0.182.0. I've tried to run Atom.exe inside this folder and the app start regularly and i have linked the .exe file to desktop. The directory \bin does not exist in ```AppData\Local\atom```

**Comment by Sigmanor** [comment]
same here 
```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Фокс\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\Фокс\AppData\Local\atom\packages\RELEASES".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   в Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   в Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Фокс\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\Фокс\AppData\Local\atom\app-0.165.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Фокс\AppData\Local\atom\app-0.165.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.165.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.165.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Фокс\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\Фокс\AppData\Local\atom\packages\RELEASES".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   в Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   в Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Фокс\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\Фокс\AppData\Local\atom\app-0.182.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Фокс\AppData\Local\atom\app-0.182.0\atom.exe]
ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Фокс\AppData\Local\atom\app-0.182.0\atom.exe: System.OperationCanceledException: Операция была отменена.
   в System.Threading.CancellationToken.ThrowOperationCanceledException()
   в Squirrel.Utility.<>c__DisplayClassf.<InvokeProcessAsync>b__e()
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb6.<<invokePostInstall>b__aa>d__b8.MoveNext()
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 0.182.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.182.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Фокс\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\Фокс\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Writing files to app directory: C:\Users\Фокс\AppData\Local\atom\app-0.183.0
IEnableLogger: Failed to invoke post-install: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\Фокс\AppData\Local\atom\app-0.184.0".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileSystemEnumerableIterator`1.CommonInit()
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.DirectoryInfo.EnumerateFiles()
   в Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion)
   в Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__bc.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<LogIfThrows>d__48.MoveNext()
```

**Comment by batjko** [comment]
For reference:

https://discuss.atom.io/t/atom-installation-error-on-windows-8-1/15050/6

https://discuss.atom.io/t/clean-install-of-atom-0-184-fails-on-windows-8-1/15126

**Comment by paulcbetts** [comment]
Is this happening all the time? Usually this happens when you try to uninstall then immediately reinstall, but atom.exe is still hanging around

**Comment by DavidA2014** [comment]
I rebooted and repeated the install of 0.184. Again I saw the 'Install has failed' message box shown in equinusocio's post above.

**Comment by paulcbetts** [comment]
Do you have an Antivirus product? Does it suck?

**Comment by andischerer** [comment]
got the same Problem with the same logmessages. After killing the hole "%LOCALAPPDATA%\Temp" folder atom installs successfully.

**Comment by basarat** [comment]
Getting the same error. Only since yesterday.

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\bas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bas\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\bas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\bas\AppData\Local\atom\app-0.165.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\bas\AppData\Local\atom\app-0.165.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.165.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.165.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\bas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bas\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\bas\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\bas\AppData\Local\atom\app-0.184.0
IEnableLogger: Failed to update local releases file: System.IO.IOException: The file exists.
```

**Comment by basarat** [comment]
> Do you have an Antivirus product? Does it suck?

Funny you should say that. I have windows defender, sort of sucks.

**Comment by basarat** [comment]
Sorry. Don't know which one of these two did it. But the following worked:

* Delete the whole of `%LOCALAPPDATA%\Temp`
* Kill windows defender

**Comment by vgturtle127** [comment]
Actually, I got the same error when I tried to install on Windows 7. Have no AV running, no other processes open, no firewall, nothing.

Using the zipped version worked fine though, so the installer is the problem.

I also tried it on my Windows 8 PC, with Windows Defender off and it still did that.

Anybody found a fix besides turning AVs off?

**Comment by equinusocio** [comment]
This issue is fixed by purging the  ```%LOCALAPPDATA%\Temp``` folder on Windows. In my temp folder there were a lot of temporary folders of atom. By deleting this folders the atom installer run ok.
@vgturtle127 Try it.

**Comment by andischerer** [comment]
PS: I cam up to the solution of purging `%LOCALAPPDATA%\Temp` by looking at the callstack. `System.IO.Path.InternalGetTempFileName(Boolean checkHost)` is failing in case of a thrown IO-Exception. 

[MSDN Note for this Exception](https://msdn.microsoft.com/de-de/library/system.io.path.gettempfilename(v=vs.110).aspx): The GetTempFileName method will raise an IOException if no unique temporary file name is available. To resolve this error, delete all unneeded temporary files.

**Comment by batjko** [comment]
Well, I wouldn't say it's the solution, since the actual root cause is
unknown and still needs to be looked into.
But at least there's an easy workaround now.

**Comment by paulcbetts** [comment]
Windows Defender should be fine, you do *not* need to disable it.

**Comment by vgturtle127** [comment]
I purged the temp directory and it still doesn't work...

Not sure what is causing the problem.

The application still works fine as I said, and it works great. The installer just keeps giving me trouble.

**Comment by basarat** [comment]
@vgturtle127 which version is it. I had trouble with updating before 182. That's why I uninstalled on this machine but couldn't install anymore till I cleared my temp directory.

**Comment by paulcbetts** [comment]
@vgturtle127 Can you paste the actual error you receive? A lot of people on these threads are self-diagnosing "the same error" when it's not actually the case

**Comment by Trudko** [comment]
I got also problem with installation https://gist.github.com/Trudko/cc5e18102664c7da1842

**Comment by DavidA2014** [comment]
Deleting the contents of "%LOCALAPPDATA%\Temp" fixed this issue for me.

**Comment by vgturtle127** [comment]
I am using the 184 installer now. I tried running CCleaner and restarting my computer. It still doesn't work.

I thought it might have had something to do with previous Atom data getting in the way, so I used Revo Uninstaller to uninstall Atom and then ran CCleaner, BleachBit, and System Ninja (latest versions) all with Winapp2.ini. I deleted all portable versions of Atom as well. I also deleted all the installers and archives containing Atom. Then I restarted. After that, I re-downloaded the latest installer (184), and tried to re-run it. This time, the installer started and displayed the error message (pictured above) but this time the log was fresh, and it was fine until it started to write data to the AppData directory. That is when it crashed and displayed the error message.

Tried the same on my Windows 8 machine and it did the same thing.

Like I said, the zip folder works fine. Just not the installer.

**Comment by paulcbetts** [comment]
@vgturtle127 Can you paste the actual error you receive on clean install please?  You don't have to run all those crazy programs to reset Atom, just delete `C:\Users\YOURNAME\AppData\Local\atom` and `C:\Users\YOURNAME\AppData\Local\SquirrelTemp` and run the installer again.

**Comment by vgturtle127** [comment]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\Turtle\AppData\Local\SquirrelTemp

in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.__Error.WinIOError()

Then I get some more garbage about System.IO, but it crashes after that...

**Comment by vgturtle127** [comment]
I also have the crash log if you would rather have that.

**Comment by vgturtle127** [comment]
Squirrel Updater log:

Program: Starting Squirrel Updater: --uninstall
Program: Starting uninstall for app: 
ApplyReleasesImpl: Starting full uninstall
LogHost: Uninstall failed to delete dir 'C:\Users\Turtle\AppData\Local\atom\..\atom', punting to next reboot: System.UnauthorizedAccessException: Access to the path 'C:\Users\Turtle\AppData\Local\atom\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<DeleteDirectory>b__2f(String file)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectoryWithFallbackToNextReboot>d__41.MoveNext()

**Comment by 50Wliu** [comment]
Are you saying you right-clicked-->"Run as Administrator"?  If so, please don't do that (in fact, in the next release of Squirrel, Squirrel will intentionally relaunch itself to run as a normal user if it detects that it has administrator permissions).

**Comment by vgturtle127** [comment]
Even if I don't, it still fails. Why will it run as a normal user in the next release? Is there a problem with UAC or something?

**Comment by JLNNN** [comment]
Go to your system preferences and start the disk-cleanup tool on c:
After the program closed itself after cleanup, I was able to update without a problem :)

**Comment by vgturtle127** [comment]
I have used that as well. I guess maybe I should try checking in my event viewer.

**Comment by sethlivingston** [comment]
I was only able to get this to work by completely uninstalling (with Revo Uninstaller) and deleting all of the files in my \Temp folder.

**Comment by paulcbetts** [comment]
This should be fixed in the latest release, this is the temp files bug again.

**Comment by fibric** [comment]
In 0.188.0 its not fixed. Maybe in 0.189.0

**Comment by paulcbetts** [comment]
@fibric Can you send in your Squirrel logs?

**Comment by fibric** [comment]
@paulcbetts On Monday. Cause have a mac at home and no remote access to my company windows machine

**Comment by sethlivingston** [comment]
I can send logs. Where are they on Windows?

**Comment by vgturtle127** [comment]
There are logs in different places depending on what log you are looking for, but I think the installation logs are kept in a directory called Atom in AppData. Or it might be ProgramData, I can't remember. But one of those directories has a directory in it called Atom. Logs will be in there.

So basically:

C:\Users\USERNAME\AppData

OR

C:\Users\USERNAME\ProgramData

You might also check the C:\Windows\Temp directory, when I checked there there were some temporary files stored there. Just in case.

Hope that helps.

**Comment by paulcbetts** [comment]
@vgturtle127 None of those are right, can you delete this comment? Squirrel logs are in `C:\Users\NAME\AppData\Local\atom\SquirrelSetup.log`

**Comment by sethlivingston** [comment]
That log doesn't change when I run the AtomSetup.exe, which fails to install.

   Program: Starting Squirrel Updater: --download https://atom.io/api/updates
   Program: Fetching update information, downloading from https://atom.io/api/updates
   CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
   FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES

I'm trying to re-install 0.188 because it didn't create any shortcuts or make `atom` available on a command prompt.

**Comment by fibric** [comment]
I remember I could install Atom after wiping my temp folder `C:\Users\<user.name>\AppData\Local\Temp\`. This was mentioned here several times. On Monday I'll restore log files from Trash and post them here.

**Comment by vgturtle127** [comment]
Wait, the installer does create files in those directories! I just checked. lol

I even did it with Process Hacker running and with the directories open.

Maybe I am wrong or have caused enough issues with the installer for it to dump debug info somewhere or something. But I swear it creates log files in those directories.

**Comment by LibertyBeta** [comment]
I'm reporting a similar issues with the most recent installer, however it doesn't create a atom direction in the appdata or fail with a log body. 

Note: I did try to uninstall after the borked update and it that didn't go well. I had to manually remove the registry for atom in several places.

**Comment by vgturtle127** [comment]
After Revo Uninstalling leftover Atom installations, using CCleaner, BleachBit, and System Ninja with Winapp2.ini, going through my registry, AppData, and ProgramData and deleting everything Atom related, restarting, re-downloading the latest Atom installer, and running it NOT as Admin, it finally worked! I don't know what I did this time, but I guess maybe the issue has been fixed? I still had issues with this installer last time I tried, but whatever it works now.

I'm guessing a temporary file that was created was causing some issue when it started the installer because I ran it as admin the first time. UAC sucks. Anyway, it works now so try what I did and see if it works for you.

**Comment by izuzak** [comment]
Reported again for 0.190.0 over in https://github.com/atom/atom/issues/6343 by @sryze.

**Comment by gvpinto** [comment]
Atom installer would just try to start-up and then disappear. I went ahead deleted C:\Users\YOURNAME\AppData\Local\atom and C:\Users\YOURNAME\AppData\Local\SquirrelTemp directories and ran the installer again. The directories were present because I had cancelled a previous installation. This resolved the issue.

**Comment by vgturtle127** [comment]
Maybe the Atom installer should put all of the files in sub-directory instead of in ProgramData/AppData?

**Comment by iUwej** [comment]
My installation worked after launching Atom set up as an admin.

**Comment by joshburgess** [comment]
This is still a problem now in December 2015. Just ran into it while trying to install Atom on a fresh install Windows 8 machine at work.

**Comment by paulalves** [comment]
I deleted the folder "%USERPROFILE%\.atom" and it worked for me, but I know that is not the best solution. =/

**Comment by vgturtle127** [comment]
I run into more problems on Windows 8-10 than on Windows 7, if that even helps a little.

**Comment by xiaoxinw** [comment]
I just closed the Atom editor and then install again

**Comment by vgturtle127** [comment]
Can this be closed? I think this issue has been solved by now, right?

**Comment by CreativeWebGuy** [comment]
Appears to still be an issue. I'm on Win7 64bit. Upon install I'm getting the same issues. I've tried all the temp deletions and permission notes above but nothing. If I pull the zip for windows it runs fine but the installer appears to be stalling. See below:
`
2016-02-18 17:55:47> Program: Starting Squirrel Updater: --install .
2016-02-18 17:55:47> Program: Starting install, writing to C:\Users\MYUSERID\AppData\Local\SquirrelTemp
2016-02-18 17:55:47> Program: About to install to: C:\Users\MYUSERID\AppData\Local\atom
2016-02-18 17:55:47> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\MYUSERID\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3d.MoveNext()
2016-02-18 17:55:47> CheckForUpdateImpl: Reading RELEASES file from C:\Users\MYUSERID\AppData\Local\SquirrelTemp
2016-02-18 17:55:47> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-02-18 17:55:47> ApplyReleasesImpl: Writing files to app directory: C:\Users\MYUSERID\AppData\Local\atom\app-1.5.3
2016-02-18 17:55:54> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
2016-02-18 17:55:54> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()<---

`

**Comment by vgturtle127** [comment]
@CreativeWebGuy Huh, I wish I could help in some way.

I just started running into the errors and issues again, so I have uninstalled Atom, cleaned my PC again, and now have a portable version in C:\atom that I use.

Does anybody have any idea what is causing this?

From what I can gather, it is the installer either not being allowed access to something, or the installer just becomes self-aware and hates anybody with a face. :disappointed_relieved:

**Comment by Zireael07** [comment]
@CreativeWebGuy: 

> System.IO.PathTooLongException

That's your problem right here and there is a separate issue for 'path too long' problems.

**Comment by CreativeWebGuy** [comment]
@Zireael07 - Completely missed that.  I was hung up on the RELEASES folder in the "from scratch load" it's looking for not being there. Didn't go much further beyond that in the log. Where I'm now hung up on is how to correct this. If I'm using a standard Win7 install and the files are attempting to load into their default location the only variable in length is the userid in the path. I'm on a domain so the folder becomes userid.domain (currently 16 char in length).  I guess at this point I just go on running in a folder in a portable format.

**Comment by Zireael07** [comment]
@CreativeWebGuy: Download the zip version from atom.io. It doesn't care about long paths.

**Comment by CreativeWebGuy** [comment]
@Zireael07: That's what I'm doing. I just wanted to add this in here to help put a finger on it for others.

**Comment by damieng** [comment]
As this has been identified as PATH too long I am closing it and providing a link to the issue tracking that https://github.com/atom/atom/issues/5109

**Comment by meghanakshathra** [comment]
I downloaded and installed the atom on windows 7.After installation it opened automatically and the next time i'm not able to open it. i"m basically not able to file the shortcut. Only .exe file is there on my downloads, and when I run it, it shows some error. can anyone please get the solution for this... :-)

**Comment by damieng** [comment]
@meghanakshathra Please open a new issue and include the exact error message/screen shot of the error.

**Comment by JohnTocher** [comment]
I had the same issue running the installer on Windows 10, 64 bit. Manually deleting most of the contents (Firefox had some files locked which couldn't be deleted) worked for me.

**Comment by gideondsouza** [comment]
I had the same issues, tried all suggested solutions. I had a virus scanner that sucks, McAfee. I disabled it's on `on access scan` and now the installer worked.

**Comment by jbnv** [comment]
I'm having this issue right now. Windows 10, up to date as of today. Atom began crashing during startup. I downloaded v1.10.2 of the installer. Tried clearing out the AppData folders mentioned above.  

Here is my log. Getting pretty much the same thing with everything I try. Says nothing about paths being too long. 
```
2016-09-23 08:40:25> Program: Starting Squirrel Updater: --install .
2016-09-23 08:40:25> Program: Starting install, writing to C:\Users\Jay\AppData\Local\SquirrelTemp
2016-09-23 08:40:25> Program: About to install to: C:\Users\Jay\AppData\Local\atom
2016-09-23 08:40:25> Program: Install path C:\Users\Jay\AppData\Local\atom already exists, burning it to the ground
2016-09-23 08:40:31> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jay\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-09-23 08:40:31> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Jay\AppData\Local\SquirrelTemp
2016-09-23 08:40:31> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-09-23 08:40:31> ApplyReleasesImpl: Writing files to app directory: C:\Users\Jay\AppData\Local\atom\app-1.10.2
2016-09-23 08:41:01> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---

2016-09-23 08:41:01> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<installPackageToAppDir>b__b1(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<<installPackageToAppDir>b__ad>d__bd.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'resources' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassb4.<>c__DisplayClassb9.<>c__DisplayClassbb.<installPackageToAppDir>b__b2(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---
<---
```

**Comment by damieng** [comment]
It does however point to paths being denied. Are you running an anti-virus?

**Comment by kavin-90** [comment]
I got same error for me its related to Disk Space lol
