### ISSUE TITLE
Use of Chrome 41 in Atom 0.189.0 breaks cursor controls for Ubuntu 14.04 in virtualized environments.

### ISSUE THREAD

**Issue by rdnewman** [atom/atom#6243]
Almost certainly because of this Chrome issue:  https://code.google.com/p/chromium/issues/detail?id=465660 (see also https://code.google.com/p/chromium/issues/detail?id=456222, https://www.virtualbox.org/ticket/13968).   Didn't have this problem in Atom in this environment before the upgrade to use Chrome 41.  Makes Atom very difficult to use in this environment.

**Comment by massayoshi** [comment]
I running Ubuntu 14.04 (installed not virtualized) and can confirm this. Sometimes when I copy and paste something into Atom it would crash. And Chrome was behaving weirdly as well. `0.188` was working fine.

**Comment by 50Wliu** [comment]
@massayoshi: To confirm, you have the *exact same bug* as @rdnewman?  It seems like you're reporting a different bug (copy/paste crash) which will be resolved in 0.190.0.

**Comment by massayoshi** [comment]
@50Wliu perhaps they are 2 different things. Like @rdnewman said, the Chrome behavior is mostly due to Chrome 41. But I faced this copy/paste crash a few times and thought the two were related.

**Comment by tinchogon34** [comment]
I'm running Ubuntu 14.10 not virtualized. When I copy from Atom and try to paste in Google Chrome Version 42.0.2311.90 (64-bit) I can't because contextual menu is broken and Google Chrome hangs finally crashing.

**Comment by 50Wliu** [comment]
@tinchogon34 your bug is entirely unrelated to this issue and has been resolved in Atom versions 0.190.0 and on.

**Comment by rdnewman** [comment]
Per this comment:  https://code.google.com/p/chromium/issues/detail?id=456222#c155, issue appears to persist with Chrome 42.   I've confirmed that Chrome 42 itself continues to have the mouse issue under VirtualBox.  There is a workaround chrome configuration documented in the above thread that might work; I don't know if that is useful from Atom to implement as a temporary workaround.  If you try it, I am happy to test a beta version of Atom on this topic if you need a tester to confirm any solution.

**Comment by rdnewman** [comment]
Chrome 43 seems to have fixed the issue.  If Atom were to upgrade its base to Chrome 43, this issue would likely no longer persist in Atom.  I think this issue's label should no longer be marked as blocked.

**Comment by thiago-sydow** [comment]
:+1: for this. Chrome 43 fixed this issue. My Atom still have this scroll behaviour.
Virtualbox, Ubuntu 15.04, Atom 0.205.0

**Comment by 50Wliu** [comment]
Atom will be upgrading to Chrome 43 in the near future, but it might take some time as a few modules like `node-spellchecker` crash on v43.

**Comment by rdnewman** [comment]
@50Wliu Thanks for the update!

**Comment by capouch** [comment]
Are atom-shell and electron perfectly in sync?  I.e. when the fixed Chrome goes into one of them, will it go into the other one simultaneously?

**Comment by 50Wliu** [comment]
@capouch atom-shell got renamed to Electron a few months back.  Electron is already on Chrome 43, but Atom hasn't updated to that Electron version yet.

**Comment by capouch** [comment]
I was confused because there is still a subdir "atom-shell" inside the Atom source tree, and that was why I asked--apparently Atom doesn't use Electron as its shell given the two separate names/filesets?

**Comment by mnquintana** [comment]
@capouch Atom's hasn't upgraded from atom-shell (ie. Electron pre-rename) to Electron yet - [it is in progress though.](https://github.com/atom/atom/pull/6877)

**Comment by capouch** [comment]
@mnquintana @50Wliu Thank you both very much.  I am very excited about both Atom and Electron; I think they are going to lead us into a whole new way of thinking about applications.  Thanks again!

**Comment by rdnewman** [comment]
Am I right to conclude that this issue (#6243) is targeted to resolution as part of #7995 since you're trying for #7877?  Excited to see this resolved soon!

**Comment by 50Wliu** [comment]
Yes, exactly :).

**Comment by rdnewman** [comment]
Yay!
