### ISSUE TITLE
Regex replace with escape \n character only works for first line

### ISSUE THREAD

**Issue by mattroberts297** [atom/atom#7004]
Using Version 0.201.0 (0.201.0) on OS X Yosemite.

Given this:
![foo bar and baz on separate lines](http://s18.postimg.org/dlrqn01vd/input.png)

When I click 'Replace All' I get this:
![the first line looking correct](http://s23.postimg.org/gstydnv6z/actual.png)

But I expected this:
![all lines looking correct](http://s22.postimg.org/wpvwe7dv5/expected.png)

Not sure if this is a bug or by design. Either way I thought I should raise it.

Cheers,
Matt.

**Comment by grandsong** [comment]
I guess it is a bug.

By the way, you can simplify your find query into `.+`. No need to use `^` and `$`.

**Comment by grandsong** [comment]
Moreover, before the bug is fixed, how can you accomplish your job?
- A generic solution is using another editor.
- For your specific need, here is a trick without any regexp.
1) select a line-break charact (move caret to the end of Line 1, and then press Shift+→); 
2) Press Cmd+D as many times as the lines are; 
3) Press ← once; 
4) Now you have a caret at the end of each line. Type `\n",`.
5) Press Home to go to the beginning of each line. Type `"`.

**Comment by mattroberts297** [comment]
Funnily, I did the exact same thing re: `"$1\\\\n"` before posting (just in case I was doing something stupid).

Thanks for the tip(s). On that note, with regards to step 2: is there a way to say 'all lines'. In the real use case I had a *largish* bash script that needed converting to cloud formation's json format.

Thanks again!

**Comment by grandsong** [comment]
Sorry to say but I don't think Step 2 can be improved so much. 

After all, it is just a backup.

If you really need to replace many, you have to use an editor with good replacement function.

---

PS: With my trick, you can, as I hope, branch out to other similar jobs. There are more benefits beyond this particular job that you have problem now.

**Comment by mysticatea** [comment]
I also encountered this problem. 

----

- Atom `0.204.0`
- Windows 7 64bit

**Comment by GPHemsley** [comment]
This is still an issue in version 1.0.2. Effectively, the backslashes are not being maintaining properly.

**Comment by GPHemsley** [comment]
Looks like this is actually an issue with [atom/find-and-replace](https://github.com/atom/find-and-replace).

See also: atom/find-and-replace#186 (and probably others).

**Comment by mnquintana** [comment]
Thanks @GPHemsley! This indeed looks like a duplicate of https://github.com/atom/find-and-replace/issues/186 – please subscribe there for updates.

**Comment by mattroberts297** [comment]
Indeed. Thanks for doing the leg work @GPHemsley.
