### ISSUE TITLE
Atom icon in the taskbar not found - replaced by windows icon for non found image

### ISSUE THREAD

**Issue by Overdrivr** [atom/atom#9618]
The issue happens all of a sudden, I suppose probably after an automatic update

![issue](https://cloud.githubusercontent.com/assets/1294805/11177834/af79e012-8c48-11e5-80e8-d751c2f57734.png)

I search for a similar issue, maybe related to #8789 ?

**Comment by mjohnsonengr** [comment]
Was mentioned in #5323 too.

**Comment by rafaelmartines** [comment]
Interesting that this happen to me again, just when a new update to Atom became available '_'

In my case I usually pin Atom at the taskbar on Windows, to fix that I unpin Atom and pin again after update

**Comment by mjohnsonengr** [comment]
Here's a possible workaround.  No guarantees because I haven't had another update to test it with yet, but this icon is version agnostic.

Create your own shortcut that points to C:\Users\<username>\AppData\Local\atom\bin\atom.cmd and give it the Atom icon.

**Comment by mixmatch** [comment]
It would be nice if the shortcut in the start menu pointed to a version agnostic executable with the proper icon. This also happens on Windows 10 when Atom is pinned. Icon becomes blank sheet of paper upon updating.

**Comment by paulcbetts** [comment]
This is a bug we've been trying to fix for forever. It's on our list for the next release to Fix It Harder

**Comment by DomS23** [comment]
This is still happening. Just happened today with my 1.4.1 update. Losing the icon and the "run in" windows option was invalid due to the update.

**Comment by jamesqo** [comment]
Yep, happening here as well.

**Comment by LiamMcArthur** [comment]
This is still happening in 1.5.3.

**Comment by damieng** [comment]
This has been addressed in Squirrel and 1.7.0 of Atom will include the new Squirrel that identifies and updates pinned task bar menu items.

**Comment by conor909** [comment]
@github, the same issue is also on git kraken (the source control product from github)

**Comment by mixmatch** [comment]
@conor909 git kraken is not a github product, the just use electron shell to build their (closed source) app

**Comment by Fania** [comment]
Still happening to me. Win 10 - Atom 1.7.2...

**Comment by errorx666** [comment]
I'm still having this issue on Atom 1.8.0-beta3 on Win 7 x64.

**Comment by mvcaaa** [comment]
For me - Atom have Pokerstars client icon(???)  instead )

![Screenshot](https://i.imgur.com/tp7lYQJ.png)

**Comment by Jimut** [comment]
Still happeing on Win 10. Atom 1.10.2
