### ISSUE TITLE
Files opened externally now opened in new window even if project window already open

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#9732]
After one of the latest Atom updates, files opened from the file system are no longer opened in one of the existing windows, but rather in a window of their own. Can this be disabled somewhere in the preferences to go back to the old behaviour? Unless improvements are made so that opening a new Atom window doesn't take 5+ seconds, it's really detrimental to your work flow if you have to wait that long for opening a single file that you just want to copy some contents from.

**Comment by izuzak** [comment]
Hey @adambuczynski, thanks for opening an issue. Would you mind providing a bit more information? There's a neat guide to help you with that:

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs

Also, a similar issue was reported and fixed a few days ago. Can you check out https://github.com/atom/atom/issues/9574 and https://github.com/atom/atom/pull/9672 and see if that fits your description? I'm going to close this for now since I think that's the same problem and it was fixed, but let me know I'm wrong. And again, please try to include more helpful information with your reports because it's really hard to provide advice when we don't even know which version of Atom you're on, or which OS you're using. Thanks

**Comment by adambuczynski** [comment]
Hi @izuzak , it was on Atom 1.2.0 for Mac OS X. I didn't think this information is relevant, as the issue was files being opened in a new window, which I assumed was a non-OS specific design decision from the Atom team.

Before positing I did a search for "new window" in the issues, and did not find a relevant ticket.

**Comment by adambuczynski** [comment]
@izuzak I think this issue still hasn't been addressed. The issues you linked don't seem to be referring to the same problem.

An additional symptom of this problem is that when having a project window open, and then opening a file from within that project through an external app (e.g. Github Desktop), it still opens a new window for that file, even though a window for that project is already open. This seems like a valid bug.

Atom 1.2.4 on Mac.

**Comment by izuzak** [comment]
Thanks for following up, @adambuczynski. Just to make sure we understand, can you post the _exact_ steps to reproduce the problem and a GIF which follows those steps to demonstrate it? Also, which version of OSX are you on exactly ("on Mac" is not :gem: clear).

**Comment by adambuczynski** [comment]
OS X 10.10.5

1. Open Atom
2. Open a project folder (e.g. ~/Sites/something)
3. Go to Finder (or any other external app)
4. Open a file from within the project folder (e.g. ~/Sites/something/somefile.js)
5. Observe how Atom opens a new window for the file, rather than opening it in the existing project window.

This wasn't a problem until 1.2.x I believe, as Atom would just open files that you opened externally in the same window.

**Comment by adambuczynski** [comment]
Could you please reopen this issue, it's really bothersome. I've provided steps to reproduce, please let me know if you need more information. Thank you!

**Comment by adambuczynski** [comment]
This also happens when dragging a file from Finder into an existing Atom window.

Also affects OS X 10.11.1

**Comment by jlecour** [comment]
I've just switched to Atom from Textmate and I missed this feature. I often use the iTerm `Cmd-clic` to open a file from my terminal and was sad to see them opened (very slowly) in a new window. It would be awesome if it would work again.

**Comment by adambuczynski** [comment]
This seems to have been fixed now in Atom 1.4.x and above.
